### ISSUE TITLE
vitualenv support?

### ISSUE THREAD

**Issue by eelkeh** [zchee/deoplete-jedi#10]
Should virtualenv work out of the box?

**Comment by zchee** [comment]
@eelkeh Hi :)

I do not use `virtualenv`, so do not know whether can use...
Maybe Neovim also does not support `virtualenv`...? (not checked)

Can you use `virtualenv` with Neovim?

**Comment by zchee** [comment]
@eelkeh I have investigated.
and I got advice from Shougo.

If you install `neovim/python-client` in `virtualenv`, Neovim python binding works fine.
Also `deoplete-jedi` will works.

So, the Already behavior is possible.
If you still do not work, Please create new issue thread with tiny `init.vim` and sample python code.

Close :)

**Comment by eelkeh** [comment]
Yes it worked after installing the neovim client in `virtualenv`! Thanks so much, maybe consider adding this to the README as loads of python devs user `virtualenv`
