### ISSUE TITLE
jedi completion does not trigger

### ISSUE THREAD

**Issue by Neo44763** [zchee/deoplete-jedi#100]
# Problem summary
I'm trying to get jedi completion to work but the only completions i get are strings in the current buffer.
like here: https://imgur.com/a/oy62s

## Expected
similiar behavior like in other autocompletions that i already have running with deoplete.
like ruby: http://imgur.com/a/INJKl
as you can see it also suggests words that are not in the current buffer

## Environment Information

 * OS: Arch Linux 4.6.0
 * Neovim version: 0.1.7

## Provide a minimal init.vim with less than 50 lines (required)
`set runtimepath+=~/.vim/plugged/deoplete.nvim/plugin/deoplete.vim/`
`set runtimepath+=~/.vim/plugged/deoplete-jedi/`
`call plug#begin('~/.vim/plugged')`
`Plug 'Shougo/deoplete.nvim'`
`Plug 'zchee/deoplete-jedi'`
`call plug#end()`
`let g:deoplete#enable_at_startup=1`
`let g:deoplete#auto_completion_start_length = 0`

`call deoplete#custom#set('jedi', 'debug_enabled', 1)`
`call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')`

There is also no difference if i don't set a runtime path for deoplete and deoplete-jedi
also no difference if using my complete init.vim
just adding
Plug 'fishbullet/deoplete-ruby'
would activate ruby completion without problems, but python stays the same

## Generate logfiles if appropriate

nvim generated a logfile called nvim-log_py3_rplugin even though i called it differently.
it's too big for pastebin and i don't see any error messages, however the format at quite bad:
https://ufile.io/eb67e

## Steps to reproduce the issue after starting Neovim (required)

 1. install neovim
 2. install deoplete-jedi
 3. check if autocomplete works

## What i tried:

:CheckHealth does not report any errors
:echo has("python") returns 1
:echo has("python3") returns 1
:UpdateRemotePlugins makes no difference
reinstalled everything multiple times (neovim, neovim-python, python2-jedi, python3-jedi)
switched from jedi from the Arch repos to pip
i also removed all vim Plugins, i thought maybe YCM jedi in vim would somehow break deoplete-jedi in neovim but no difference

i never had any error messages in logs or in vim, nothing that hinted that something is not working.
ONLY THING that seems strange to me:
When reinstalling only deoplete-jedi with Plug, it shows a git message in the command window of vim:
https://imgur.com/a/AVWKw
The git message is at the bottom of the screenshot. No other Plugin does that. Is this normal?

I would really appreciate any help on this. At this point i don't know what else to try so i'm opening this issue.
This is my first issue ever created on Github so please tell me if i did something wrong, also let me know if you need more information. I know the infos i gave probably won't let you solve this problem instantly but i don't know what else to give you. Also please let me know if i missed something obvious.

Many Thanks in advance

**Comment by monkoose** [comment]
It is jedi problem itself.
Archlinux few days ago updated python3.5 to python3.6 and there is some problemds not only with jedi. Git version of jedi already has fix.

**Comment by Neo44763** [comment]
This indeed solved the problem. Thanks for your help

**Comment by Shougo** [comment]
Jedi patch is merged.  Closed.
