### ISSUE TITLE
Fix cwd when loading server

### ISSUE THREAD

**Issue by blueyed** [zchee/deoplete-jedi#102]
I've noticed that deoplete-jedi will use Neovim's `cwd` when loading the server, which means that this depends on `:lcd` and when the server gets started (when doing it lazily, e.g. when entering insert mode).

When using `pyenv`, this might result in different `python` interpreters being used.

While this can be powerful in the context of restarting deoplete-jedi with another interpreter, it is rather confusing in its current state.

1. A first step here might be to allow for configuration of the `python` prog (https://github.com/zchee/deoplete-jedi/blob/cdbe0902d646c37e68d0b2967b445c993b78cd32/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L464).
This should be looked at when restarting then, too - allowing to change it without restarting Neovim (https://github.com/zchee/deoplete-jedi/blob/cdbe0902d646c37e68d0b2967b445c993b78cd32/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L500).

2. Is there a way to get Neovim's startup directory later?  This could be used then to change into before running the `python` prog.  This would make the automatic detection (in the case of `pyenv` or other tools using the current working directory) more deterministic.

**Comment by Shougo** [comment]
I think deoplete-jedi should use `context['cwd']`.

**Comment by blueyed** [comment]
> I think deoplete-jedi should use `context['cwd']`.

But that still is the `getcwd()` when the context is created?!  (https://github.com/Shougo/deoplete.nvim/blob/cad288a242c5a84c398d0035d159366c6acae8ed/autoload/deoplete/init.vim#L217)
The problem is not that the cwd changes while deoplete-jedi is being called, but that the cwd is not Neovim's startup dir.

**Comment by tweekmonster** [comment]
Does `:cd`, `:lcd`, and `:tcd` actually cause `pyenv` to update the interpreter?  From my understanding, this is something that happens in the interactive shell.

**Comment by blueyed** [comment]
> Does :cd, :lcd, and :tcd actually cause pyenv to update the interpreter? From my understanding, this is something that happens in the interactive shell.

It's not updating it, but has an effect when being called initially.
My use case is lazily loading deoplete-jedi, so it might not happen during loading vimrc already, but only later.

**Comment by zchee** [comment]
I don't understand all yet, but I think the related thing, so I'll leave the comment.

If use `contex['cwd']`, but that's sometimes different actual current `cwd` path. (yes, when lazy loading)
I was used that on the deoplete-go, but it seems to passes wrong absolute filepath to `gocode`. so I was fallback to use `self.vim.current.buffer.name`
https://github.com/zchee/deoplete-go/commit/128bab523362a0767aaddb83c4673d65f41e436b

**Comment by tweekmonster** [comment]
@blueyed Okay, I think I understand the problem you're describing now.  What's making this confusing for me is I don't understand how `pyenv` is related.  The only issue I can foresee from this is project modules not being seen by the server during completion.

Anyways, wouldn't this be easier as a change in Deoplete that sets a variable when nvim starts?  Like `deoplete#startup_pwd = getcwd()`.  Then it should be available via `context['vars']`.

**Comment by blueyed** [comment]
> how pyenv is related

It is about using `pyenv local`, which allows to configure project settings, using a dotfile to indicate that.
This results in a different `python` being used by the shim.

> `deoplete#startup_pwd = getcwd()`

This fails also short when deoplete is loaded lazily.
For this I think support from Neovim/Vim would be required.

**Comment by zchee** [comment]
@tweekmonster 
As @blueyed said,
> This fails also short when deoplete is loaded lazily.
> For this I think support from Neovim/Vim would be required.

Yeah, I think so, too. (only for `pyenv` issue. not related deoplete-go)

**Comment by tweekmonster** [comment]
> It is about using pyenv local

I use `pyenv local` for basically everything, but I never experienced issues with it.  I just tested with `:cd ..` and `echo system('pyenv which python')` and now I have a full appreciation for what you're talking about.  Sorry!

Okay, so I think the only important thing `cwd` would tell is that the server *might* need to restart.  What deoplete-jedi needs to do is track `cwd` and if it changes, evaluate the python interpreter path.  During evaluation, `pyenv` needs to be detected and if it exists, don't use `VIRTUAL_ENV` to determine anything (since it doesn't change after nvim is started) and use `pyenv prefix` instead.

**Comment by zchee** [comment]
@tweekmonster SGTM.
BTW,
> What deoplete-jedi needs to do is track cwd and if it changes, evaluate the python interpreter path

out of curiosity, Do you think how much the overhead of tracking `cwd` behavior?

**Comment by tweekmonster** [comment]
> how much the overhead of tracking cwd behavior?

```python
if context['cwd'] != self.cwd:
    self.cwd = context['cwd']
    check_python_and_maybe_restart_server()
```

It shouldn't be anything perceptible since the server already restarts after so many completions.

**Comment by blueyed** [comment]
I wonder if it makes sense to allow for specifying the `python` prog to be used explicitly (point 1)?

Also, I could imagine having multiple servers running at the same time, i.e. for two different virtualenvs in the same session.

**Comment by zchee** [comment]
@tweekmonster 
> It shouldn't be anything perceptible since the server already restarts after so many completions.

Ah, that's just `if` check. I see, np.
Even if we check it every time, but will overhead don't happen.

**Comment by zchee** [comment]
@blueyed @tweekmonster @Shougo 
Hey, I found now, Is that new API would be useful for solving this problem? (but after the release stable version with included this API)
[RDY] New event: `DirChanged`: https://github.com/neovim/neovim/pull/5928

**Comment by blueyed** [comment]
@zchee 
I think it would still look at the context of requests.
`DirChanged` could be used to proactively notify the server to be (re)started though maybe.. but OTOH there is no reason to do so in case you're just changing dirs for some reason.

**Comment by zchee** [comment]
@blueyed Ah, Hmm. correct :(
It seems that was me jumping to conclusions \o/

**Comment by tweekmonster** [comment]
> I wonder if it makes sense to allow for specifying the python prog to be used explicitly (point 1)?

I think the configured interpreter should always take precedence.

> Also, I could imagine having multiple servers running at the same time, i.e. for two different virtualenvs in the same session.

Not out of the question, but it would require a router and a way to keep the warm caches separate.  This might be better as a separate PR after this is resolved.

> Hey, I found now, Is that new API would be useful for solving this problem?

I was looking at that too, but it's only useful in VimL since this feature could be easily emulated by checking `context['cwd']` in `on_event()`.  `DirChanged` also wouldn't be backward compatible with stable builds of nvim.

**Comment by zchee** [comment]
@tweekmonster 
> I was looking at that too, but it's only useful in VimL since this feature could be easily emulated by checking context['cwd'] in on_event(). DirChanged also wouldn't be backward compatible with stable builds of nvim.

Yeah, I'd thought again about this. Surely the same result, and use this API was meaningless in this case.

---

BTW that API is very interesting :) Maybe useful for the another project.

**Comment by Shougo** [comment]
> [RDY] New event: DirChanged: neovim/neovim#5928

The feature is merged.
I will add the support in deoplete.

**Comment by zchee** [comment]
@Shougo Thanks.

**Comment by Shougo** [comment]
@zchee Can you implement the worker restart when cwd is changed?

**Comment by Shougo** [comment]
I have implemented the feature in deoplete.
