### ISSUE TITLE
Fails to start server due to "no module names deoplete"

### ISSUE THREAD

**Issue by languitar** [zchee/deoplete-jedi#104]
# Problem summary

When starting to edit the first python file. deoplete-jedi fails to start its server with the message:
```
2017-01-18 11:04:24,709 [DEBUG @ msgpack_stream.py:send:33] 29070 - sent [0, 4, 'nvim_err_write', ('[deoplete] Error when loading source jedi: Failed to start server (python -u /home/languitar/.local/share/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py --desc-length 0 --debug  --debug-level 0): Server exited with b\'Traceback (most recent call last):\\n  File "/home/languitar/.local/share/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 24, in <module>\\n    from deoplete.deoplete import SourceInitError\\nModuleNotFoundError: No module named \\\'deoplete\\\'\\n\': error: 1. Ignoring.\n',)]
```

## Expected

It works ;-)

## Environment Information

 * OS: archlinux 64
 * Neovim version:

```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

neovim-python installation are up to date and `:UpdateRemotePlugins` has been called.

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Steps to reproduce the issue after starting Neovim (required)

 1. `:e` test.py
 2. `i`

## Upload the logfile(s)

[logfile_py2_script.txt](https://github.com/zchee/deoplete-jedi/files/713573/logfile_py2_script.txt)
[logfile_py3_rplugin.txt](https://github.com/zchee/deoplete-jedi/files/713572/logfile_py3_rplugin.txt)
[logfile_py3_script.txt](https://github.com/zchee/deoplete-jedi/files/713571/logfile_py3_script.txt)
[deoplete.log.txt](https://github.com/zchee/deoplete-jedi/files/713574/deoplete.log.txt)

**Comment by blueyed** [comment]
Please update.
Fixed in https://github.com/zchee/deoplete-jedi/commit/6240de812f06263524f46379ad08a0d3d539730f.

**Comment by languitar** [comment]
Yikes, ok. When prepared this report the fix wasn't yet available.

Thanks.

**Comment by blueyed** [comment]
I see.
Sorry for the bump, happy Vimming.

**Comment by zchee** [comment]
@languitar Sorry too as an owner. We will take care in future.

@blueyed Thanks for respond to issue :D
