### ISSUE TITLE
server: Implements a automatically clear (old) cache, or adding ClearCache command

### ISSUE THREAD

**Issue by zchee** [zchee/deoplete-jedi#106]
When some users have old cache, it seems to deoplete-jedi's server using old cache even if update jeid submodule or changed cache behavior, such as https://github.com/zchee/deoplete-jedi/issues/93#issuecomment-278539429.
So, that users using old cache, and get wrong completion candidates.

I saw json cache file have the `time` and `version` variable, but deoplete-jedi's server does not uses it?
Sorry, I'll check the server implements later, but /cc @tweekmonster

**Comment by zchee** [comment]
discussed @blueyed on https://github.com/zchee/deoplete-jedi/pull/105#issuecomment-278610630

**Comment by blueyed** [comment]
I could imagine to include the Jedi version in there, not just the Python major/minor one.

**Comment by Shougo** [comment]
What is the status?

**Comment by Shougo** [comment]
Cache feature is not needed.
