### ISSUE TITLE
Can't get completions with last update

### ISSUE THREAD

**Issue by monkoose** [zchee/deoplete-jedi#113]
# Problem summary
After the last commit #105 deoplete-jedi doesn't work at all. It doesn't complete anything.
I cleared the cache + used `git submodule update --init` - didn't help.

## Expected
Get completions.

## Environment Information
 * OS:  ArchLinux
 * Neovim version: 0.1.7

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set runtimepath+=$HOME/.local/share/nvim/site/dein/repos/github.com/Shougo/dein.vim

if dein#load_state(expand('$HOME/.local/share/nvim/site/dein'))
  call dein#begin(expand('$HOME/.local/share/nvim/site/dein'))
  call dein#add('Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('zchee/deoplete-jedi')
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
let g:deoplete#enable_at_startup = 1
let g:python3_host_prog = '/usr/bin/python'

```

**Comment by Shougo** [comment]
Hm.  It seems works for me.

@blueyed @tweekmonster Ping.

**Comment by Shougo** [comment]
@monkoose Please upload the sample Python source code and the reproduce ways.

**Comment by monkoose** [comment]
@Shougo is my minimal init.vim correct?

**Comment by Shougo** [comment]
It seems collect.

**Comment by monkoose** [comment]
In my situation i can't get any completions in any python file. In new one or any other. So it is pointless to provide some.
If you can get completions with this minimal init.vim so it is definitely something wrong on my side.

**Comment by Shougo** [comment]
I cannot get `re` module candidates, but I can get `os` module candidates.
I don't know why.

**Comment by monkoose** [comment]
Ah ye, can get os candidates too.

**Comment by Shougo** [comment]
Jedi diff is too long.
I think the change is not well tested in deoplete-jedi side.
(It should be tested in the branch...)

If @blueyed cannot fix the problem, I will revert https://github.com/zchee/deoplete-jedi/pull/105.

**Comment by Shougo** [comment]
> Ah ye, can get os candidates too.

>  It doesn't complete anything.

The above is wrong :-)

**Comment by monkoose** [comment]
Yes, sorry. Didn't work with os in my files.
But like almost any other can not complete `math` `random` `re` etc

**Comment by tweekmonster** [comment]
Sounds like the problem are C modules.  I'll take a look when I have some free time today.

**Comment by tweekmonster** [comment]
There were actually more issues than just C modules.  Jedi's classes have changed a little.  I'm looking into it now.

**Comment by monkoose** [comment]
@tweekmonster Thank You, seems working.

**Comment by Shougo** [comment]
Seems working.
