### ISSUE TITLE
Get rid of param from completions

### ISSUE THREAD

**Issue by monkoose** [zchee/deoplete-jedi#116]
Some enhancement suggestion.
Before jedi version 0.10 in completions we had something like this
`math.pow(x, y)`
After jedi version 0.10 we have this `param` word before every parameter
`math.pow(param x, param y)`
So completions get too long and actually distracting. Would be much better to ignore them.

**Comment by blueyed** [comment]
Isn't this a Jedi issue after all?

**Comment by monkoose** [comment]
@blueyed maybe.
I thought it's a feature or something.

**Comment by blueyed** [comment]
Yes, I am not sure either.. just a guess..
Comes through here: https://github.com/zchee/deoplete-jedi/blob/4ec734efb8902f5d109e379f8cdd97e8bf2e9422/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L388-L398.

**Comment by monkoose** [comment]
Ok, we can have there something like that:
```python
                    if desc.startswith('param'):
                        desc = desc[5:].strip()
```

So it's up to you guys, do we need this? I actually use this for now, i can create PR if this suggestion suits you.

**Comment by monkoose** [comment]
So noone else thinks that this `param` is distructing?

**Comment by Shougo** [comment]
OK.  I will check the behavior

**Comment by Shougo** [comment]
Reproduced.

>                     if desc.startswith('param'):
>                        desc = desc[5:].strip()
>                    params.append(desc)

I have tested the code, but it does not work.
"param" is displayed.  I don't know why.

**Comment by Shougo** [comment]
This param seems jedi bug.

`os.uname(param)` is displayed as the candidates.

**Comment by Shougo** [comment]
I will fix the issue.  But @monkoose your patch does not work for me.
I will research the problem more.

**Comment by Shougo** [comment]
In some module(os,re), the patch does not work.
I don't know why.
In some module(builtin functions, time), works though.

**Comment by monkoose** [comment]
Can you name me this modules?
did you use it after this line https://github.com/zchee/deoplete-jedi/blob/4ec734efb8902f5d109e379f8cdd97e8bf2e9422/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L397
```python
                    if '\\n' in desc:
                        desc = desc.replace('\\n', '\\x0A')
```

**Comment by Shougo** [comment]
> Did you use it after this line https://github.com/zchee/deoplete-jedi/blob/4ec734efb8902f5d109e379f8cdd97e8bf2e9422/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L397

Yes, I did.

> I will check(os, re) a little bit later.

Please check it.

**Comment by Shougo** [comment]
> Actually jedi started with 0.10 sometimes shows wrong parameters. I opened an issue in jedi repo, but noone responds yet.

Hmmm.....

**Comment by Shougo** [comment]
> but jedi shows it like this arange(param start, param stop, param step, param, param dtype). Notice this blank param.

Reproduced for me.

**Comment by monkoose** [comment]
> In some module(os,re), the patch does not work.

Works for me.
![](http://i.imgur.com/QfjjpGm.png)
![](http://i.imgur.com/DwiPfJW.png)

But actually jedi is somekind broken i noticed. It sometimes doesn't show some parameters, like in os.fsencode - deoplete jedi shows(and jedi itself - checked in VSCode) it as STATEMENT not a function.
So this new jedi 0.10 version has alot of bugs.

**Comment by Shougo** [comment]
> So this new jedi 0.10 version has alot of bugs.

Hm....

**Comment by monkoose** [comment]
So what it your problem with my implemetation? Do you still have param in like `re.search`? So it looks like `re.search(param pattern, param string, param flags=0)`?

**Comment by Shougo** [comment]
The deoplete-jedi result seems cached for me.
I don't know the reason though.
Your patch is better than current implementation.
I will include it.

**Comment by monkoose** [comment]
> The deoplete-jedi result seems cached for me.

Yes, this is a problem. You should always remove the cache if you change something.

**Comment by Shougo** [comment]
> Yes, this is a problem. You should always remove the cache if you change something.

How do I remove the cache?

**Comment by monkoose** [comment]
`rm -rf ~/.cache/deoplete/jedi` - works for me.

**Comment by Shougo** [comment]
It works.  Thank you.

> but jedi shows it like this arange(param start, param stop, param step, param, param dtype). Notice this blank param.

It is jedi problem.  But I will fix it in deoplete-jedi.

**Comment by monkoose** [comment]
deoplete-jedi actually already has version validation. 
And it is stored in each module json cache file. I don't get why it isn't implemented that if version is wrong then it rewrite this file? 
Or maybe even better to get global cache config and if version in it isn't the current then wipe all cache directory? 
I can check for this implementation later if you want.

**Comment by monkoose** [comment]
I investigated a little, `pydoc` shows numpy.arange as `numpy.arange([start,] stop[, step,], dtype=None)` too. arange impelemented in c and path for it `numpy/core/multiarray.so`. So i suppose it appeared with python3.6. Maybe changes in Numpy C-API itself or i dunno.
