### ISSUE TITLE
Show function signature with param suggestion (somewhat like pycharm)

### ISSUE THREAD

**Issue by purpleP** [zchee/deoplete-jedi#117]
Suppose I have code that look like that where `|` is cursor as always.

```
text = '123'
def some(foo, bar, baz):
      pass
```

And I type `some(|)`. At this point you can have additional pattern triggered. Something like `[a-zA-Z][a-zA-Z0-9_]*\(` which is to say I'm possibly typing inside of function call. Then knowing the cursor position you can know for sure whether or not I'm inside a function call. In this case I'm really inside a function call so you can show `({foo}, bar, baz)` where `{}` is to shows me the name of a parameter that I will probably type. Suppose after that I type `some(f`. It would be reasonable to show me param name amongst the suggestions, so I would see `foo=` and after pressing `tab` or something I will complete it into `some(foo=`. Suppose I typed some value into that parameter and proceeded into second parameter `some(foo='foo', `. At this point you can recognize that I typed first parameter and want to type another, so you can show `(foo, {bar}, baz` etc.

With a little bit of parsing (maybe jedi even already does that in api) or maybe recursive regexes it's possible to understand at what parameter of the function user is now. In any way you can at least show the signature when user is at the beginning of a new word that is `some(|` or `some(foo, |` and that would help a lot. That's actually basically the only feature I really miss from pycharm.

**Comment by monkoose** [comment]
jedi-vim actually can show param list and highlight current(not always right) in the command line. 
And i get parameters suggestions before anything esle inside functions. But they are completed with `=` for sure.

**Comment by Shougo** [comment]
You can use echodoc for it.

https://github.com/Shougo/echodoc.vim

**Comment by purpleP** [comment]
@monkoose @Shougo showing signature on the command line also isn't optimal, because human field of clear vision is pretty small and the command line is in the bottom, so it's a nice workaround, but only a workaround. In case of jedi-vim it can't show signatures on the command line (probably because ale plugin shows errors there. And it can't show signatures in the popup probably because I have `au CompleteDone * pclose` without which popup isn't closed properly every once in a while (standard suggesion of using InsertLeave doesn't work reliably for some reason)

I on the other hand showed that you can achieve a real solution to a problem using only vim autocomplete popup.

**Comment by Shougo** [comment]
If you want to need the feature, it needs neovim UI extension.
It is not implemented yet.

> jedi-vim actually can show param list and highlight current parameter(not always right) in the command line.

This is hack.  I don't recommend to use it.

**Comment by Shougo** [comment]
So, this is not deoplete-jedi issue.  It should be https://github.com/neovim/neovim/issues/396.
If neovim supports the feature, deoplete and deoplete-jedi can support it.

**Comment by purpleP** [comment]
@Shougo Again, I'm saying that this is possible without adding anything new to vim/neovim.

**Comment by Shougo** [comment]
> @Shougo Again, I'm saying that this is possible without adding anything new to vim/neovim.

OK.  I don't understand.

> In this case I'm really inside a function call so you can show ({foo}, bar, baz) where {} is to shows me the name of a parameter that I will probably type. 

Please describe it.
Where the feature show the function parameter?

**Comment by Shougo** [comment]
Note: I don't want to use highlight hack in jedi-vim.

**Comment by purpleP** [comment]
@Shougo 

> Please describe it.
> Where the feature show the function parameter?

in the completion popup. You see the idea is very simple. When user is at the start of new word like `some(|`) or `some(foo, |` you don't show anything in the popup anyway. So why not show function parameters at this point until user typed something. When he starts typing you can show relevant autocompletions including (using my previous example again) `bar=` if he typed `b`

**Comment by monkoose** [comment]
@purpleP I will just describe my thoughts. And i understand that maybe someone(as you) will prefer this popup help.
Myself, i don't need some another popup window always shown inside every function, for me its more annoying then helpful, more often i just know which argument i need to use. And if i need some help, then i just can look at command line. For me it's less descructing workflow.
Actually now i use `echodoc`, thanks to Shougo. 
And i do believe that jedi-vim `let g:jedi#show_call_signatures = "1"` doesn't work in neovim(actually it didn't work when i tested while ago). But this feature should work in vim as you described - popup inside a function(or i didn't understand what do you even want).

**Comment by purpleP** [comment]
@monkoose 
1. Jedi-vim shows call signatures via hack (it messes with buffer).
2. This plugin is for neovim, right? So in neovim we don't even have that hack available.
3. If you think some users might not like this feature - you can make it optional, right?
4. You wouldn't need any other popup window, that's what's different from pycharm in my approach.
5. You say you can look at command line, but what if there is an error on the same line from linter? I don't think you can control who would have displayed message at the command line: linter or echodoc.

**Comment by monkoose** [comment]
@purpleP 
5. I use Ale too, and in Insert mode any error or warning message dissapear from command line(same with Syntastic). So there is no any problem with echodoc or jedi-vim interaction.

**Comment by purpleP** [comment]
@monkoose I might as well would if you would help with jedi api. I have a few questions about it.
1. How to get function signature from it.
2. Is there ability know what parameter use is entering?

**Comment by monkoose** [comment]
I'm not a collaborator of deoplete-jedi and i don't know jedi as well.
Ask @tweekmonster @blueyed @zchee and maybe @Shougo 
What about your 2 item - i suppose you can't do it with jedi. Vim-jedi shows correctly only positional arguments(VSCode has the same problem as well and even shows this annoying popup with wrong current parameter). As example: you can write `print("Hello, World!", end=|` but it will highlight `sep`, not `end` and so on.

**Comment by Shougo** [comment]
@purpleP OK.  I get it.
But I don't think `in the completion popup` is good.
It easily conflicts with the auto completion.
I want to display the param with the completion.
So, the extended UI is needed.

**Comment by Shougo** [comment]
> You say you can look at command line, but what if there is an error on the same line from linter? I don't think you can control who would have display message at the command line: linter or echodoc.

I can extend echodoc to display it in tabline, statusline, ...

**Comment by purpleP** [comment]
@Shougo I thought that it would conflict, but it actually wouldn't, because:
a) possible param name is a valid completion, right?
b) you can show function signature  as a `info` (as you call it in docs) of a candidate, so it can be `bar    param   [jedi]   some(foo, {bar}, baz)`

Just so we clear on that - I completely understand that what I'm suggesting is more a workaround of vim's inability to show arbitrary widgets (which neovim hopefully will fix in 2.0 release) and that it's stretching a bit vims current completion widget by displaying function signature as a `info`. But what I'm saying is that I think it isn't stretching it too far. In case function signature is really long plugin can show `some(foo, {bar}...)` or something like that.

**Comment by Shougo** [comment]
> a) possible param name is a valid completion, right?

It is not.  But it is always displayed in popup menu.  It is very annoying for me.
It is just workaround and tricky.

>  In case function signature is really long plugin can show some(foo, {bar}...) or something like that.

Yes.  So I don't think the plugin should display the long parameter in abbr.

**Comment by purpleP** [comment]
@Shougo Excuse me, but for python possible param name is definitely a valid completion, because there is a good chance that user would use named arguments. The annoying part is subjective, so we shouldn't discuss it unless we create a user survey.

**Comment by Shougo** [comment]
I also think show function signature is needed.
So I have created echodoc plugin.
But it should not be on popupmenu.

**Comment by purpleP** [comment]
@Shougo On a side note - I don't see what languages `echodoc` supports.

**Comment by Shougo** [comment]
> @Shougo On a side note - I don't see what languages echodoc supports.

This is good question.
echodoc is extensible and it can support many languages like deoplete.

**Comment by monkoose** [comment]
> On a side note - I don't see what languages echodoc supports.

As i think it only shows parameters of function that shown in completions(so deoplete sources should show them or echodoc will show nothing). 
So it can support like any language that has some completion engine api that can return all parameters and with right deoplete source implementation.
Maybe @Shougo can correct me.

**Comment by Shougo** [comment]
> So it can support like any language that has some completion engine api that can return all parameters and with right deoplete source implementation.

Yes.

And it is extensible.
echodoc supports ruby documentation.

**Comment by Shougo** [comment]
It can be done by echodoc.

**Comment by Drakirus** [comment]
> PR's are more then welcome.

Might not be relevant anymore, but I proposed a PR to echodoc that show the the function signature in a jedi-like display.
https://github.com/Shougo/echodoc.vim/pull/70 
It doesn't mess with the buffer, no highlight hack is required.
