### ISSUE TITLE
Autocomplete lists only some options from imported module

### ISSUE THREAD

**Issue by smurfendrek123** [zchee/deoplete-jedi#122]
# Problem summary
I'm trying to get autocomplete for Gtk.ListBox() and deoplete only gives me Listboxwindow(self made class), listboxrow, and listboxrowwithdata (self made class). Also i don't know if this is a jedi issue or a deoplete issue.

Jedi is definitely working, example with the import statement: http://imgur.com/a/LKjbu (also why are there doubles, and how do i remove the doubles?)

## Expected
I also expect to get autocompletion for Gtk.ListBox()

## Environment Information
 * OS: Linux, fedora 25
 * Neovim version: 0.1.7

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')

#self provided
set laststatus = 0
set ruler
set completeopt-=preview
```

## Steps to reproduce the issue after starting Neovim (required)

 1. Open up the provided python file: https://bpaste.net/show/36202879e962
 2. try to autocomplete Gtk.List to Gtk.ListBox()

## Screen shot (if possible)
http://imgur.com/a/UXgCl

**Comment by Shougo** [comment]
> (also why are there doubles, and how do i remove the doubles?)

This is deoplete feature.
`[A]` source candidate priority is high.  So it is on the top.
But deoplete-jedi adds the additional information.
So deoplete cannot remove the doubles.

**Comment by Shougo** [comment]
>  Also i don't know if this is a jedi issue or a deoplete issue.

Please test it in vim-jedi.
I think it is jedi issue.

**Comment by smurfendrek123** [comment]
https://github.com/davidhalter/jedi-vim/issues/279

I thnk i found the relevant bug report at jedi.

I'll close this since it does indeed seem to be a jedi issue

**Comment by Shougo** [comment]
OK.
