### ISSUE TITLE
Jedi doesn't trigger on `from X import Y` reliably

### ISSUE THREAD

**Issue by wbthomason** [zchee/deoplete-jedi#127]
# Problem summary

When editing a Python file and typing `from X import` (where `X` is some module), Deoplete offers no jedi completions for the object `Y` being imported from module `X`.

## Expected

Typing `from X import |` (where | is the cursor) should offer completions for objects inside module `X` at |.

## Environment Information

 * OS: Arch Linux
 * Neovim version: v0.2.0

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

 1. Open a Python file
 2. Type `from multiprocessing import ` (or any other module instead of `multiprocessing`)
 3. Observe that Deoplete's only completion is `import`
 4. Backspace to place the cursor as `from multiprocessing import|`
 5. Wait a few seconds
 6. Press `space` and note that Deoplete now correctly suggests completions from jedi

## Screen shot (if possible)

**Observed Behavior:**
![jedi_completions](https://user-images.githubusercontent.com/3729908/26840834-81a8967e-4ab5-11e7-91b0-79ae4a826b49.png)

**Expected Behavior (obtained via steps 4-6 in the above reproduction procedure):**
![jedi_completions_expected](https://user-images.githubusercontent.com/3729908/26840841-8564a14a-4ab5-11e7-9335-c15bacf9b0ac.png)

## Upload the logfile(s)
[deoplete.log.txt](https://github.com/zchee/deoplete-jedi/files/1055806/deoplete.log.txt)

## Additional Notes

I considered that this could be happening because of the time required for jedi to gather candidates. This could still be the cause, but I think it isn't likely to be because this behavior is consistently observed for even trivially small modules (i.e. not something huge like numpy).

**Comment by blueyed** [comment]
Can somehow reproduce it, using `from multiprocessing import `.

With `from os import ` it works though always from the beginning.

This is the log.
Only the last entries from 21:55:28 made it show up the completions really:
```
2017-06-06 21:54:27,729 DEBUG    (deoplete.jedi.worker.Thread-2) Got work
2017-06-06 21:54:27,736 DEBUG    (deoplete.jedi.server) Line: 2, Col: 21, Filename: '…/vim/plugged/deoplete-jedi/t.py'
2017-06-06 21:54:27,745 DEBUG    (deoplete.jedi.worker.Thread-2) Completed work
2017-06-06 21:54:27,746 DEBUG    (deoplete.jedi.cache) Processed: ('multiprocessing', 'package')
2017-06-06 21:54:30,074 DEBUG    (deoplete.jedi.cache) Input: "from multiprocessing import "
2017-06-06 21:54:30,074 DEBUG    (deoplete.jedi) Key: ('multiprocessing', 'package'), Refresh: True, Wait: False, Async: False
2017-06-06 21:54:30,075 INFO     (deoplete.jedi) gather_candidates t = 1.202563ms, µ = 27.647554ms, σ = 45.101795ms)
2017-06-06 21:54:30,075 DEBUG    (deoplete.jedi.worker.Thread-1) Got work
2017-06-06 21:54:30,077 DEBUG    (deoplete.jedi.server) Line: 2, Col: 28, Filename: '…/vim/plugged/deoplete-jedi/t.py'
2017-06-06 21:54:31,446 DEBUG    (deoplete.jedi.worker.Thread-1) Completed work
2017-06-06 21:54:31,447 DEBUG    (deoplete.jedi.cache) Processed: ('multiprocessing', 'package')
2017-06-06 21:55:17,563 DEBUG    (deoplete.jedi.cache) Input: "from multiprocessing import"
2017-06-06 21:55:17,566 DEBUG    (deoplete.jedi) Key: ('multiprocessing', 'package'), Refresh: False, Wait: False, Async: False
2017-06-06 21:55:17,568 INFO     (deoplete.jedi) gather_candidates t = 5.084316ms, µ = 25.988834ms, σ = 46.078181ms)
2017-06-06 21:55:28,533 DEBUG    (deoplete.jedi.cache) Input: "from multiprocessing import "
2017-06-06 21:55:28,536 DEBUG    (deoplete.jedi) Key: ('multiprocessing', 'package'), Refresh: False, Wait: False, Async: False
2017-06-06 21:55:28,538 INFO     (deoplete.jedi) gather_candidates t = 4.580873ms, µ = 26.522512ms, σ = 45.751197ms)
```

**Comment by wbthomason** [comment]
@blueyed Interesting. I verified that I also always get completions from the start with `from os import `, but they are notably the wrong completions - I get the completions you'd expect for `import ` (i.e. the list of available top-level modules) rather than a list of objects in the `os` module. Does that match what you see?

**Comment by blueyed** [comment]
Yes.
And when trying it now again it even just provided just "import" there, too.

I've updated deoplete yesterday, which might be related?! I've not seen this issue before.

**Comment by wbthomason** [comment]
I have seen this issue for at least a week. I update Deoplete (and my other plugins) pretty regularly. Given that, I think this has been present at least since https://github.com/Shougo/deoplete.nvim/commit/61fca6ac087dd78549084a81b2baacff6138dccc and https://github.com/zchee/deoplete-jedi/commit/9188f51c52ec5b241e349c84890b2e289858af8f.

**Comment by blueyed** [comment]
Deleting the cache seems to fix it: `rm ~/.cache/jedi -rf`

**Comment by wbthomason** [comment]
Deleting the cache partially fixed the incorrect results being returned for `from os import ` for me, but did not fix the issue where only `import` is offered at first. Further, the results for `from os import ` still included modules that they should not have - the change was that the contents of the `os` module were now also included in the results.

**Comment by blueyed** [comment]
The cache is actually at `~/.cache/deoplete/jedi` (fixed it above).
I was bisecting when trying that, so maybe something is causing the cache to go bad after all?
(Jedi itself also uses a cache, which might be involved here, too - `~/.cache/jedi`).

Seems to be fine for me now.

**Comment by blueyed** [comment]
I was confused to see `abc` with the `from os import `, but `os` imports it, and also `sys`, `errno` etc, so they show up because of that.

**Comment by wbthomason** [comment]
Right, that's what confused me at first. Deleting both the Deoplete and Jedi caches still only fixes the completions offered for `from os import |`. I still get only `import` offered as a completion for `from os import |`, `from multiprocessing import |`, etc.

**Comment by meiralins** [comment]
![deoplete-jedi](https://user-images.githubusercontent.com/4183188/27846512-3d3c72d4-610e-11e7-94e9-ebb44e6117ee.gif)
I've created this gif, just to clarify whats going on.

**Comment by novelview9** [comment]
I have exactly the same problem like below gif.
it comes with import keyword[jedi]
![image](https://user-images.githubusercontent.com/14916432/28206612-8e710038-68c1-11e7-8430-7865a87fdac9.png)
If I put one more word or space, it works ok.  
does anybody solve this problem?

**Comment by Shougo** [comment]
@novelview9 Please test #130.

**Comment by novelview9** [comment]
Done! on that PR branch, working great!

**Comment by Shougo** [comment]
OK.  I will merge it.

**Comment by meiralins** [comment]
Working great. I think this issue can be closed.

**Comment by wbthomason** [comment]
I agree, the fix is working perfectly. Thank you! Closing.
