### ISSUE TITLE
g:deoplete#sources#jedi#show_docstring does not seem to be effective

### ISSUE THREAD

**Issue by azag0** [zchee/deoplete-jedi#129]
# Problem summary

The docstring appears even when the option is set to 0.

## Expected

It should not appear.

## Environment Information

 * OS: macOS 10.12.6 beta
 * Neovim version: 0.2.0

## Provide a minimal init.vim with less than 50 lines (required)

```vim
filetype off
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/vimproc', {'do': 'make'}   " subprocess api for plugins
    Plug 'Shougo/deoplete.nvim'         " async autocompletion
    Plug 'zchee/deoplete-jedi'
call plug#end()
filetype plugin indent on
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#show_docstring = 0
```

## Steps to reproduce the issue after starting Neovim (required)

 1. Let jedi autocomplete `os.abort`, the pop up appears.

## Screen shot (if possible)

On KEY-DOWN pressed:

![screen shot 2017-06-15 at 14 50 33](https://user-images.githubusercontent.com/940353/27181977-0d978368-51da-11e7-9e89-123dda8a3c53.png)

**Comment by Shougo** [comment]
`set completeopt-=preview`

**Comment by azag0** [comment]
But that turns off the preview globally for everything, doesn't it?

Also, this doesn't mean that the jedi specific option isn't effective.

**Comment by Shougo** [comment]
```
- `g:deoplete#sources#jedi#show_docstring`: Shows docstring in preview window.
  Default: `0`
```

It does not mean disable preview feature.
It just disable `docstring`.  Do you know docstring?
The preview window feature cannot be disabled.
Because, echodoc uses this feature.

**Comment by azag0** [comment]
Ah. I'm sorry. Should have thought more about it.
