### ISSUE TITLE
can't find the python binary

### ISSUE THREAD

**Issue by teto** [zchee/deoplete-jedi#134]
# Problem summary

I am on revision 56528fd1238bbf2f9363f16710d0936703dc9eab

When starting nvim, I systematically get:
```
[deoplete] Error when loading source jedi: Failed to start server (python -u /  
       ↳ home/teto/.local/share/nvim/site/pack/deoplete-jedi/rplugin/python3/deoplete/    
       ↳ sources/deoplete_jedi/server.py --desc-length 0 --debug  --debug-level 0):       
       ↳ [Errno 2] No such file or directory: 'python'. Ignoring.
```
## Expected
No error

## Environment Information

 * OS: nixos 17.03
 * Neovim version: NVIM v0.2.1-dev 

Nixos is a bit of a peculiar OS that runs every program in some kind of virtualized environment. For instance neovim runs with python3 available in `g:python3_host_prog=
/nix/store/macg539i39wpzxhysp1lmvv7zfx6nqsb-neovim-master/bin/nvim-python3` but there is no `python` binary in path. I don't know wether deoplete-jedi retrieves its binary from deoplete or by itself but at some point it should use  g:python3_host_prog otherwise it might pickup a wrong python.

**Comment by Shougo** [comment]
OK.  It should be fixed.

**Comment by Shougo** [comment]
Hm.  Please configure `deoplete#sources#jedi#python_path`.
