### ISSUE TITLE
Neovim freezes on dot completion in large libraries

### ISSUE THREAD

**Issue by pfrcks** [zchee/deoplete-jedi#135]
[nvim-log_py2_script.txt](https://github.com/zchee/deoplete-jedi/files/1366669/nvim-log_py2_script.txt)
[nvim-log_py3_rplugin.txt](https://github.com/zchee/deoplete-jedi/files/1366670/nvim-log_py3_rplugin.txt)

# Problem summary

`import matplotlib.` freezes neovim. tried changing server timeout option but that also did not help.

## Expected

The results to be cached after one attempt.

## Environment Information

 * OS: Ubuntu 16.04
 * Neovim version: v0.2.0

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
let s:config_dir = expand('~/.config/nvim/')
let s:bundle_dir = s:config_dir . '/bundle/'

call plug#begin(s:bundle_dir)

Plug 'zchee/deoplete-jedi'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:deoplete#enable_at_startup = 1
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

 1. import matplotlib.

 2.
 3.

**Comment by Shougo** [comment]
I will test it later.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
