### ISSUE TITLE
No completions for any library

### ISSUE THREAD

**Issue by vyzyv** [zchee/deoplete-jedi#140]
# Problem summary
There are no completions from libraries (either default or third party like numpy or pandas).
Actually numpy completions are the only one working (library got parsed and json file was correctly produced (no clue how?)), no other json file has been created (after deleting numpy.json, cannot produce it again). 

## Expected
Normal completion for deoplete, not only for module names.

## Environment Information

 * OS: Arch Linux
 * Neovim version: 0.2.2

## Provide a minimal init.vim with less than 50 lines (required)

```vim
call plug#begin()
Plug 'zchee/deoplete-jedi'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:jedi#auto_initialization = 0
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 0
let g:deoplete#enable_camel_case = 1

let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
call deoplete#custom#source('jedi', 'debug_enabled', 1)
```

## Generate logfiles if appropriate

Logfile provided as gist:
https://gist.github.com/vyzyv/8e362e17eafd6401687eb030a5d657a3

## Steps to reproduce the issue after starting Neovim (required)

 1. Use Arch Linux with newest packages
 2. Use minimial init.vim above
 3. Start with import re
 4. Try re. and nothing

## Other informations

- Using asynchronous linter ALE, though seems unlikely to be the cause of this problem.
- Deoplete is unable to create json specific library files, located in $HOME/.cache/deople/jedi/3.6
- All :CheckHealth passed, except for $TERM not using screen-256colors (using just screen)
- Tried increasing server_timeout using line below, no difference
`let g:deoplete#sources#jedi#server_timeout = 1000000`
- Jedi installed from official Arch repo, newest version with parso

**Comment by Shougo** [comment]
I have tested the below init.vim.  But I cannot reproduce the problem.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set rtp+=~/.cache/dein/repos/github.com/zchee/deoplete-jedi/
" set rtp+=~/src/LanguageClient-neovim/

let g:jedi#auto_initialization = 0
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 0
let g:deoplete#enable_camel_case = 1

let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
call deoplete#custom#source('jedi', 'debug_enabled', 1)
```

**Comment by Shougo** [comment]
jedi is working correctly?
Please test deoplete and deoplete-jedi in another machine.

**Comment by vyzyv** [comment]
Yes, other completion plugins using jedi (e.g. https://github.com/maralla/completor.vim) work correctly (except for larger libraries like Pandas/Tensorflow/numpy).

**Comment by Shougo** [comment]
@vyzyv It is not the same.
completor.vim uses system jedi library.  But deoplete-jedi uses system installed jedi library.

**Comment by Shougo** [comment]
@vyzyv 

> Please test deoplete and deoplete-jedi in another machine.

Please do this.

I will test it in Manjaro Linux machine later though.

**Comment by vyzyv** [comment]
Ok, will test it later on another Arch machine (well, I don't have access to any non-arch, though I think it won't be a problem).

**Comment by vyzyv** [comment]
Works on another Arch machine, any idea what could be the root of the problem here? Any further logs needed?

**Comment by Shougo** [comment]
> Works on another Arch machine, any idea what could be the root of the problem here? Any further logs needed?

Oh, I don't know why...
It seems your environment problem.
I cannot fix it.

You should re-install the plugins.
