### ISSUE TITLE
Add command to restart server

### ISSUE THREAD

**Issue by blueyed** [zchee/deoplete-jedi#150]
It would be nice to have a command to reload the server, for debugging and to pick up config changes, like `deoplete#sources#jedi#extra_path` and `$VIRTUAL_ENV`.

Needs to go into deoplete.nvim likely, since it has to go through its g:deoplete#_channel_id?!

Related: https://github.com/Shougo/deoplete.nvim/issues/613

**Comment by Shougo** [comment]
Why the command is needed?
I think deoplete-jedi can check the variables changes in `gather_candidates()`.
What is the problem?

**Comment by blueyed** [comment]
Ok, I will try that.

**Comment by tpict** [comment]
This would be a fantastic addition. For an example of its use, [here's something](https://tompicton.com/vim-venv/) I wrote about using the kill server command in Completor to make completions match the virtualenv of the project you're working on.

**Comment by blueyed** [comment]
The new Jedi (0.12+) has support for better virtualenv support, and we should use the approach to restart the server in case the environment changes (or use servers per environment in general).
It would make sense then probably to have only one (set of) server(s) per environment, across different Neovim instances.
