### ISSUE TITLE
PyQt5 completion problem

### ISSUE THREAD

**Issue by happycorsair** [zchee/deoplete-jedi#151]
Hi all!
Thank you for your effort on Neovim development!

# Problem summary
Very strange completion of PyQt5 imports. Please, take a look at those screenshots. Deoplete-Jedi provides me with the same list of modules every time. It may happen so, that this problem is related not only to PyQt5 package.

## Expected
Correct completion.

## Environment Information
 * OS: Gentoo
 * Neovim version: 
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -march=x86-64 -mtune=generic -O2 -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2_build/config -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2_build/include

...

Features: +acl +iconv +jemalloc +tui 
```

## Minimal init.vim
```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Screenshots
![screenshot_2018-02-16_11-03-19](https://user-images.githubusercontent.com/5007838/36298969-ddf670bc-130b-11e8-94b1-b943caa482dd.png)
![screenshot_2018-02-16_11-03-46](https://user-images.githubusercontent.com/5007838/36298970-de3338da-130b-11e8-866b-bd528badaff0.png)

## Logfiles
[deoplete.log](https://github.com/zchee/deoplete-jedi/files/1730589/deoplete.log)
[nvim-log_py3_rplugin.log](https://github.com/zchee/deoplete-jedi/files/1730590/nvim-log_py3_rplugin.log)

**Comment by Shougo** [comment]
Hm.  The completion candidates seems broken.

**Comment by happycorsair** [comment]
Thank you for such a quick answer. By the way, there is one more strange thing - almost every possible completion is handled as a module.

![screenshot_2018-02-16_12-20-45](https://user-images.githubusercontent.com/5007838/36300915-1f3ef924-1314-11e8-8e06-c38eb24505d1.png)

If you need any help in investigation of this issue, I can help you.

**Comment by Shougo** [comment]
import module search seems broken.
But I don't know why.
The module search function is very complex for me.

**Comment by Shougo** [comment]
> Thank you for such a quick answer. By the way, there is one more strange thing - almost every possible completion is handled as a module.

Please test it in the other jedi based completion plugin.
It seems jedi problem.

**Comment by Shougo** [comment]
I get the original problem.

The 2nd problem, I think it is not deoplete-jedi problem.

**Comment by Shougo** [comment]
https://github.com/zchee/deoplete-jedi/issues/151#issuecomment-366184008

I have checked the implementation.
It is jedi problem.

**Comment by happycorsair** [comment]
Hah, exactly so. I've just run ipython (now it has Jedi-based autocompletion) - the second bug (everything is module) exists there also.

Is it possible to fix the first one?

**Comment by Shougo** [comment]
Please test the patch.

```diff
diff --git a/rplugin/python3/deoplete/sources/deoplete_jedi.py b/rplugin/python3/deoplete/sources/deoplete_jedi.py
index f7ab608..d15178b 100644
--- a/rplugin/python3/deoplete/sources/deoplete_jedi.py
+++ b/rplugin/python3/deoplete/sources/deoplete_jedi.py
@@ -84,12 +84,7 @@ class Source(Base):
             self.workers_started = True

     def get_complete_position(self, context):
-        pattern = r'\w*$'
-        if context['input'].lstrip().startswith(('from ', 'import ')):
-            m = re.search(r'[,\s]$', context['input'])
-            if m:
-                return m.end()
-        m = re.search(pattern, context['input'])
+        m = re.search(r'\w*$', context['input'])
         return m.start() if m else -1

     def mix_boilerplate(self, completions):
diff --git a/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py b/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py
index e48b073..ca66807 100644
--- a/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py
+++ b/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py
@@ -380,9 +380,9 @@ def cache_context(filename, context, source, extra_path):
         cinput = context['input'].lstrip()
         m = re.search(r'^from\s+(\S+)(.*)', cinput)
         if m:
-            if m.group(2).lstrip() in 'import':
-                cache_key = ('importkeyword~', )
-                return cache_key, extra_modules
+            # if m.group(2).lstrip() in 'import':
+            #     cache_key = ('importkeyword~', )
+            #     return cache_key, extra_modules
             import_key = m.group(1) or 'import~'
         elif cinput.startswith('import ') and cinput.rstrip().endswith('.'):
             import_key = re.sub(r'[^\s\w\.]', ' ', cinput.strip()).split()[-1]
```

**Comment by Shougo** [comment]
@zchee Can you check the patch?

**Comment by happycorsair** [comment]
@Shougo It stopped to make wrong
```python

**Comment by happycorsair** [comment]
It stopped making shitty completions in this situation:
```python
from PyQt5.QtWidgets.
```
But real completion does not work as expected (in IPython does):
```python
import PyQt5.QtWidgets.{we expect completion} # no completions
```
```python
from PyQt5.QtWidgets import {we expect completion} # no completions
```

**Comment by Shougo** [comment]
@happycorsair I don't want to test PyQt.
Please create the new example without PyQt.
I think it is not PyQt related.

**Comment by happycorsair** [comment]
@Shougo I've tested a number of other packages I use (pyserial, numpy, pyautogui), I've found no way to reproduce the problem. Later I'm going to test more. For a while, I have no evidence, that is not PyQt related.

Setting ```g:deoplete#sources#jedi#server_timeout``` doesn't help.

**Comment by zchee** [comment]
@happycorsair
> I've tested a number of other packages I use (pyserial, numpy, pyautogui), I've found no way to reproduce the problem. Later I'm going to test more. For a while, I have no evidence, that is not PyQt related.

I understand your means. IIRC, I had same problem in `import peachpy.x86_64`.
I’ll debug it.

Just to confirm, if we write following code,
```python
from PyQt5.QtWidgets.
```
next completion list is should not display, right? or, correctly is show another completions than `from PyQt5.`? If so, Could you tell me correct word list?

**Comment by zchee** [comment]
@Shougo got it, will do.

**Comment by happycorsair** [comment]
@zchee Hi! 
I'd recommend you to look at IPython completion lists (it's Jedi-based), usually it works pretty well.
So, in our case we should have:
1. ```from PyQt5.``` Here we should get the following:
![screenshot_2018-02-16_16-35-23](https://user-images.githubusercontent.com/5007838/36310015-c3b5a386-1337-11e8-9bd2-1cff50c5c502.png)
2. ```from PyQt5.QtWidgets.``` You are right, no completion should be provided here.
3.  ```from PyQt5.QtWidgets import ``` Here we should have smth. like:
![screenshot_2018-02-16_16-35-58](https://user-images.githubusercontent.com/5007838/36310133-1d0bd81a-1338-11e8-852d-c02a928721e4.png)

**Comment by zchee** [comment]
@happycorsair Thanks for the easy to understand screenshot, will check.

**Comment by happycorsair** [comment]
@zchee  NP. Just drop a line, if I can help somehow.

**Comment by happycorsair** [comment]
Hi, @Shougo 
You've definitely improved the situation. The issue has been fixed:
![screenshot at 2018-08-10 15-39-13](https://user-images.githubusercontent.com/5007838/43958360-ca84158e-9cb3-11e8-8d9e-0227040647df.png)
But, sadly, another thing is broken:
![screenshot at 2018-08-10 15-39-58](https://user-images.githubusercontent.com/5007838/43958382-ecd5ccc2-9cb3-11e8-9531-36a1f2dd9c40.png)
Thank you very much!!! Looking forward for new bugfixes.

**Comment by zabulazza** [comment]
@happycorsair , +1 for this issue, despite I have somehow managed to get this fixed before update.

**Comment by Shougo** [comment]
#184 fixes it.
