### ISSUE TITLE
Problem with pandas

### ISSUE THREAD

**Issue by FelipeMarcelino** [zchee/deoplete-jedi#157]
# Problem summary
I have a problem with autocomplete pandas. When I type pandas. or pandas.r , there is a error message:

"Restarting server because it's taking too long"

It is only for pandas.

## Expected

Autocomplete with pandas

## Environment Information

 * OS: LInux
 * Neovim version:0.2.2

## Provide a minimal init.vim with less than 50 lines (required)
set nocompatible

" True colors no nvim"
set termguicolors

" Modifica o título do terminal
set title

" Adiciona número ao lado esquerdo do arquivo
set number

" Números relativos
set relativenumber

"Número de linhas de comandos que serão guardads
set history=10000

"Exibe comandos incompletos na parte inferior
set showcmd

"Flag global para search and replace
set gdefault

"Smartcase search
set smartcase

"Ignorecase search
set ignorecase

"Pula para o primeiro cateres non-blank
set nostartofline

"Remove delay
set timeoutlen=1000 ttimeoutlen=0

"Encoding File
set fileencoding=utf-8

"Splits 
set splitright
set splitbelow

"Ativa plugins e identação por tipo de arquivo
filetype plugin indent on

"Ativa syntax
syntax on

"Remove swap file e backup
set noswapfile
set nobackup
set nowb

" Showmode
set showmode

"Habilidar undo mesmo que a sessão seja finalizado
silent !mkdir ~/.vimrc/backups > /dev/null 2>&1
set undodir=~/.vimrc/backups
set undofile

"Indentação
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
set smartindent
set nofoldenable

"Abreviações
cnoreabbrev Wq wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Qa qa
cnoreabbrev Bd bd
cnoreabbrev bD bd
cnoreabbrev wrap set wrap
cnoreabbrev nowrap set nowrap
cnoreabbrev t tabe
cnoreabbrev T tabe
cnoreabbrev f find
cnoreabbrev F find

"Autocommands
if has("autocmd")
    autocmd bufwritepost generals.vim source ~/.vimrc/init.vim
    autocmd bufwritepost keys.vim source ~/.vimrc/init.vim
    autocmd bufwritepost plugins.vim source ~/.vimrc/init.vim
    autocmd bufwritepost settings_plugins.vim source ~/.vimrc/init.vim
endif

"Deoplete 
let g:deoplete#enable_at_startup = 1

deoplete log

[nvim-log_py3_rplugin.log](https://github.com/zchee/deoplete-jedi/files/1791419/nvim-log_py3_rplugin.log)
[deoplete.log](https://github.com/zchee/deoplete-jedi/files/1791414/deoplete.log)

**Comment by Shougo** [comment]
Dup of https://github.com/zchee/deoplete-jedi/issues/155.
