### ISSUE TITLE
Update wiki article: Setting up Python for Neovim

### ISSUE THREAD

**Issue by last-partizan** [zchee/deoplete-jedi#159]
Hello, i'm using deoplete-jedi for some time with vim, and still not followed recommended way of installing from this article: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

I was using globally installed neovim modules and --system-site-packages in virtualenvs, but today i come up with great idea.

If modules is installed globally on my system (i use arch and we have python-neovim and python3-neovim in repos), it's better to just do this:

```
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
```

And everything will work just fine, with or without virtualenvs.

I think this should be added somewhere near "Simple setup" to save people from horrors of pyenv.

btw, thanks for great plugin :+1:

**Comment by zoresvit** [comment]
Hi, @last-partizan! I also use Arch with system neovim modules, but for some reason I still have to install `neovim` inside virtualenv even if `g:python3_host_prog` is set :(

**Comment by last-partizan** [comment]
Hi @zoresvit 
Looks like it was working back then, but now it doesn't. I'm using --system-site-packages now.

**Comment by blueyed** [comment]
@last-partizan 
It works for me like you described.
How doesn't it work anymore?
Are we talking about Neovim setup only, or deoplete-jedi also / in particular?

See also `:checkhealth` in Neovim btw.

**Comment by last-partizan** [comment]
@blueyed 

I'm talking about vim and deoplete-jedi. I getting error like this in python3 new venv:
```
[vim-hug-neovim-rpc] failed executing: pythonx import neovim
[vim-hug-neovim-rpc] Vim(pythonx):Traceback (most recent call last): 
```

neovim works just fine.

**Comment by blueyed** [comment]
Isn't it a problem with vim-hug-neovim-rpc?

**Comment by Shougo** [comment]
It is not deoplete-jedi problem.
You don't install neovim package.

**Comment by last-partizan** [comment]
Well, problem is - i have installed neovim packages.
```
> pacman -Q python-neovim python2-neovim 
python-neovim 0.2.6-1
python2-neovim 0.2.6-1
```
And it works flawlessly in neovim, so - my problem probably with vim-hug-neovim-rpc or vim/pythonx settings.
