### ISSUE TITLE
numpy: Restarting server because it's taking too long

### ISSUE THREAD

**Issue by doubleloop** [zchee/deoplete-jedi#167]
# Problem summary
deoplete works fine for many completions but does not work for some packages in particular for numpy. The error:
```
Restarting server because it's taking too long
```

## Environment Information
* NVIM v0.3.0-1193-ge46534b42
* deoplete.nvim  3fb71d7
* deoplete-jedi 3f510b467baded4279c52147e98f840b53324a8b
```
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/home/doubleloop/.virtualenvs/nvim/bin/python"
  - INFO: Executable: /home/doubleloop/.virtualenvs/nvim/bin/python
  - INFO: Python2 version: 2.7.14
  - INFO: python-neovim version: 0.2.6
  - OK: Latest python-neovim is installed: 0.2.6
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/home/doubleloop/.virtualenvs/nvim3/bin/python3"
  - INFO: Executable: /home/doubleloop/.virtualenvs/nvim3/bin/python3
  - INFO: Python3 version: 3.6.5
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6
```
on both venvs:
```
jedi               0.12.0
numpy              1.14.3
```
also on both venvs jedi seems to work ok:
```
time python -c "import jedi; print(jedi.Script('import numpy as np; np.').completions())"
[<Completion: abs>, <Completion: absolute>, <Completion: absolute_import>, ...
1.46s user 0.05s system 77% cpu 1.946 total
```
## minimal init.vim

```vim
let g:python_host_prog = "/home/doubleloop/.virtualenvs/nvim/bin/python"
let g:python3_host_prog = "/home/doubleloop/.virtualenvs/nvim3/bin/python3"
set runtimepath+=/home/doubleloop/.local/share/nvim/plugged/deoplete.nvim/
set runtimepath+=/home/doubleloop/.local/share/nvim/plugged/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

## Steps to reproduce
Just try to autocomplete `np.`
```
import numpy as np
np.
```

## Screen
error case:
![error](https://user-images.githubusercontent.com/2602750/39640015-f2243b1e-4fc9-11e8-9729-dfb242f15412.png)
working case:
![working](https://user-images.githubusercontent.com/2602750/39640044-0c46d27c-4fca-11e8-936a-25485ededc3f.png)

## Logs
[deoplete.log](https://github.com/zchee/deoplete-jedi/files/1975215/deoplete.log)
[nvim-log_py3_rplugin.log](https://github.com/zchee/deoplete-jedi/files/1975216/nvim-log_py3_rplugin.log)

**Comment by Shougo** [comment]
https://github.com/zchee/deoplete-jedi/issues/93

**Comment by Shougo** [comment]
You should change `g:deoplete#sources#jedi#server_timeout` value.
The default is 10s.

**Comment by Shougo** [comment]
https://github.com/zchee/deoplete-jedi/pull/125
