### ISSUE TITLE
"Error when loading source jedi: Failed to start server" when using virtualenv at Windows

### ISSUE THREAD

**Issue by thiamteck** [zchee/deoplete-jedi#170]
# Problem summary

Code completion work well on python files without virtualenv, but when virtualenv activated, deoplete hit error on noevim startup as below;

![deoplete-jedi-virtualenv](https://user-images.githubusercontent.com/535474/41819752-796ca484-77f8-11e8-86a9-abbdb1ce8940.png)

The problem shall be due to the path it pointed to is contains front slash which is interpreted as command option in Windows.

![invalid_parameters](https://user-images.githubusercontent.com/535474/41819794-4a4e558e-77f9-11e8-822d-9435c76d0fe2.png)

## Expected

Code completion shall still work with virtualenv

## Environment Information

 * OS: Windows 10
 * Neovim version: 0.3.0
 * Python version: 3.6

## Provide a minimal init.vim with less than 50 lines (required)

```vim
let g:python3_host_prog=expand('$HOME/AppData/Local/nvim/python_env/neovim3/Scripts/python.exe')
let g:python_host_prog=expand('$HOME/AppData/Local/nvim/python_env/neovim/Scripts/python.exe')

call plug#begin('~/AppData/Local/nvim/plugged')
if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
endif 
Plug 'zchee/deoplete-jedi'

" Use deoplete.
let g:deoplete#enable_at_startup = 1
```

## Steps to reproduce the issue after starting Neovim (required)

 1. at command prompt, activate virtualenv : `env\Scripts\activate`
 2. open a python file: `nvim test.py`
 
## Screen shot (if possible)

![deoplete-jedi-virtualenv](https://user-images.githubusercontent.com/535474/41819792-4a20646c-77f9-11e8-9282-2167cfad9313.png)
![invalid_parameters](https://user-images.githubusercontent.com/535474/41819794-4a4e558e-77f9-11e8-822d-9435c76d0fe2.png)

**Comment by Shougo** [comment]
Please test #171.

**Comment by thiamteck** [comment]
hi @Shougo , after some testing, I found even the path for python program is different in Windows, and below is the modifications that was tested working (starting line 475):

``` python
        if 'VIRTUAL_ENV' in os.environ:
            if os.name == 'nt':
                prog = os.path.join(self.env['VIRTUAL_ENV'], 'Scripts', 'python')
            else:
                prog = os.path.join(self.env['VIRTUAL_ENV'], 'bin', 'python')
        elif python_path:
            prog = python_path
        else:
            prog = 'python'

        self.cmd = [prog, '-u', os.path.normpath(__file__),
                    '--desc-length', str(desc_len)]
```

Complete file at: https://gist.github.com/thiamteck/9e9a0eac1aa27c021af8f4d395cfd1a9

Thank you.

**Comment by blueyed** [comment]
JFI: upgrading Jedi would help here, too - it has better virtualenv support itself.
https://github.com/zchee/deoplete-jedi/issues/156

For jedi-vim I've started working on commands to dynamically select a specific version.
Jedi has an API to get virtual envs / system envs.
https://github.com/davidhalter/jedi-vim/pull/836

**Comment by thiamteck** [comment]
hi @blueyed , I am already using Jedi 0.12.0, will also give jedi-vim a try.

**Comment by Shougo** [comment]
@blueyed I know.
But jedi in deoplete-jedi is not updated yet.

So I have merged the changes.

> For jedi-vim I've started working on commands to dynamically select a specific version.
> Jedi has an API to get virtual envs / system envs.
> davidhalter/jedi-vim#836

When starts for deoplete-jedi...

**Comment by blueyed** [comment]
@thiamteck 
Out of curiosity: `__file__` on Windows might contain mixed slashes?
(Only the `rplugin/python/deoplete` part has them.)
