### ISSUE TITLE
Remove extra symbols from word completion

### ISSUE THREAD

**Issue by tweekmonster** [zchee/deoplete-jedi#18]
Completion adds a `(` or `.` at the end of the word.  This has been more annoying than useful in Python.

For example:

```python
from module import BaseClass

class Subclass(
```

If I want to add `BaseClass` as a subclass, the completion will add this:

```python
class Subclass(BaseClass.
```

I use the following to assist with completions:

```vim
inoremap <expr> ( pumvisible() ? "\<c-y>()\<c-\>\<c-o>h" : "("
inoremap <expr> ) pumvisible() ? "\<c-y>)" : ")"
inoremap <expr> . pumvisible() ? "\<c-y>." : "."
```

When I accept the completion using `)`, in the example above I end up with:

```python
class Subclass(BaseClass.)
```
The other problem is Python properties.  Jedi shows them as functions, which causes an open parenthesis to be incorrectly added to the completion.

I think this should be removed completely to let the user decide on what to do.

**Comment by zchee** [comment]
@tweekmonster I was poor physical condition yesterday.
I'll reply later :)

**Comment by zchee** [comment]
@tweekmonster I understand.
and, I mistook `deoplete.nvim` implementation.

I want to use `converter_auto_paren`.
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin%2Fpython3%2Fdeoplete%2Ffilters%2Fconverter_auto_paren.py

> I use the following to assist with completions:

FYI, I use `neopairs.vim`
https://github.com/Shougo/neopairs.vim

So, I think good behavior is

1. If user wants automatically completion bracket, set  
`call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])`
2. `deoplete-jedi` add `(` in `abbr` or `info`
3. `converter_auto_paren` add `(` in `word`
4. If user use `neopairs.vim`, automatically completion `)`

and, remove `(` and `.` completion in `deoplete-jedi`.

WDYT?

**Comment by tweekmonster** [comment]
@zchee I'll have to try neopairs to understand fully, but it sounds good so far.

It looks like `abbr` or `info` needs to have `()` in it for the converter.  This will leave a problem with Python properties.

In case you don't know:

```python
class Example(object):
    @property
    def example_property(self):
        return True

e = Example()
print(e.ex
```

When you do a completion on the last line, Jedi will report that `example_property` is a function, which is correct.  But, it would mean deoplete-jedi will add `()` to it for `abbr`.  This needs to be addressed before using `converter_auto_paren` is recommended.

I think it's possible to distinguish properties from functions and improve some other ambiguous descriptions.  I'm going to try and submit a PR if I'm successful.

**Comment by zchee** [comment]
@tweekmonster Hm, That is correct.
Certainly, this example result is `print(e.example_property()`. last char's `()` is not necessary.

> I'm going to try and submit a PR if I'm successful.

OK, I look forward to your pull request :) Thanks.

**Comment by zchee** [comment]
@tweekmonster 
> For now I think it's best to simply remove ( and . from completion.

OK, I will remove `(` and `.` completion later.

**Comment by zchee** [comment]
@tweekmonster 

Off topic:
FYI, [Shougo/echodoc.vim](https://github.com/Shougo/echodoc.vim) also good `deoplete.nvim` support plugin.
Try use it :)

**Comment by tweekmonster** [comment]
>FYI, Shougo/echodoc.vim also good deoplete.nvim support plugin.

Holy shit that's a good plugin now that I tried it.  I needed this a long time ago.  Thanks!  I thought it was for showing the full documentation of a completion when I read the docs for deoplete.nvim.  echodoc.nvim doesn't really describe itself either.

**Comment by zchee** [comment]
@tweekmonster :grin: :tada:
