### ISSUE TITLE
permission error when trigger completion choice list

### ISSUE THREAD

**Issue by purejoy** [zchee/deoplete-jedi#181]
# Problem summary
Get a permission error  when  trigger completion choice list.
[deoplete] Traceback (most recent call last):
  File "/Users/ray/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 226, in _gather_results
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/Users/ray/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/ray/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 233, in gather_candidates
    self.extra_path)
  File "/Users/ray/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py", line 404, in cache_context
    elif is_package(import_key):
  File "/Users/ray/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py", line 341, in is_package
    paths = sys_path(refresh)
  File "/Users/ray/.local/share/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py", line 326, in sys_path
    ], stdout=subprocess.PIPE)
  File "/Users/ray/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/Users/ray/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
Error from jedi: PermissionError(13, 'Permission denied').  Use :messages / see above for error details.
## Environment Information

 * OS: Mac OS  10.13.5
 * Neovim version:0.3

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim/
set runtimepath+=~/.local/share/nvim/plugged/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Steps to reproduce the issue after starting Neovim (required)

 1. edit a python source file
 2.
 3.

## Upload the logfile(s)
[deoplete.log](https://github.com/zchee/deoplete-jedi/files/2173837/deoplete.log)

**Comment by blueyed** [comment]
See https://github.com/zchee/deoplete-jedi/pull/174.
Please try to help finding out why `python_path` ends up being empty.

**Comment by blueyed** [comment]
Also please consider trying https://github.com/zchee/deoplete-jedi/pull/160.

**Comment by blueyed** [comment]
Also the result from this patch would be useful:

```diff
diff --git i/rplugin/python3/deoplete/sources/deoplete_jedi/server.py w/rplugin/python3/deoplete/sources/deoplete_jedi/server.py
index 72b32d3..8f0f56e 100644
--- i/rplugin/python3/deoplete/sources/deoplete_jedi/server.py
+++ w/rplugin/python3/deoplete/sources/deoplete_jedi/server.py
@@ -475,7 +475,11 @@ def __init__(self, desc_len=0, short_types=False, show_docstring=False,
         self.env = os.environ.copy()
         self.env.update({'PYTHONPATH': self._make_pythonpath()})
 
+        if python_path == '':
+            raise Exception('Client: python_path 1: %r', python_path)
         python_path = python_path or 'python'
+        if python_path == '':
+            raise Exception('Client: python_path 2: %r', python_path)
 
         self.cmd = [python_path, '-u', os.path.normpath(__file__),
                     '--desc-length', str(desc_len)]
```

Please also consider digging around a bit yourself - apparently you seem to be a Python developer.. :)

**Comment by Shougo** [comment]
@purejoy  Please test current master.

**Comment by purejoy** [comment]
@Shougo the issue is fixed after the update. Thanks you guys!
 BTW, do you guys need any other additional context information to dig into this issue?

**Comment by blueyed** [comment]
@purejoy 
I'm glad it worked out.
1. it would be nice if you could bisect it to a) the commit that broke it for you, and b) the commit that fixed it, using git-bisect
2. with the broken commit the output from the patch above might be insightful

It is probably somethings simple/stupid, but I'd really like to know.

**Comment by blueyed** [comment]
Ah, nevermind.
The traceback goes through the cache handler, and 9ac673f likely set it to an empty value then.
I guess/assume 00af6d3 fixed it then.

**Comment by purejoy** [comment]
@blueyed 
00af6d3 fix 
2b5ff12 broke 
![2018-07-09 10 46 05](https://user-images.githubusercontent.com/3711998/42428250-6b6baa1a-8365-11e8-9f55-81294ce4d402.png)

**Comment by blueyed** [comment]
@purejoy 
Thanks, but I think you've missed the last step.. anyway, glad it is solved.
