### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by henices** [zchee/deoplete-jedi#186]
Server exited with 1. stderr=[  File "/home/henices/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sourc
es/deoplete_jedi/server.py", line 556                                                                                                                                                         
    err.decode()) from exc                                                                                                                                                                    
                     ^                                                                                                                                                                        
SyntaxError: invalid syntax

**Comment by alok** [comment]
I get this too.

**Comment by blueyed** [comment]
You should not use Python 2.
Likely due to `python` pointing at it.
Please configure `g:deoplete#sources#jedi#python_path` for now.
https://github.com/zchee/deoplete-jedi#options

https://github.com/zchee/deoplete-jedi/pull/189 should fix it.

**Comment by caporta** [comment]
@blueyed https://github.com/zchee/deoplete-jedi#options provides "default values" in the descriptions of each setting, but when i `echo` for the value, they're unset by default. is this intended behavior?

**Comment by blueyed** [comment]
Yes.  They should be even unset by default, no?
The defaults get used in the handler then.
