### ISSUE TITLE
Duplicate self.mark

### ISSUE THREAD

**Issue by zchee** [zchee/deoplete-jedi#19]
Sometimes `self.mark` is duplicate.
In https://github.com/zchee/deoplete-jedi/blob/master/tests/test.py.

![screenshot 2016-03-19 00 22 49](https://cloud.githubusercontent.com/assets/6366270/13882623/98f5a2a4-ed69-11e5-8566-01100c46acf5.png)

Maybe, buffer cached module will be duplicate.

If set
```vim
let g:deoplete#sources#jedi#enable_cache = 0
```
does not occur.

I will debug later.
/cc @tweekmonster

**Comment by tweekmonster** [comment]
Strange.  The old cache should be completely replaced, not updated.  I can't reproduce your example, but I also noticed that it sometimes doesn't add `[jedi]` for some completions until I try completing again.

**Comment by zchee** [comment]
@tweekmonster
I was type
`c` - `<BS>` - `s` - `<BS>` - `t`
Maybe reproduced it.

I debbuging now.

**Comment by zchee** [comment]
@tweekmonster 
I found the regularity.
This seems more likely to occur in Python `builtins`.
but, Sometimes it occurs even otherwise :(

![screenshot 2016-03-19 01 08 15](https://cloud.githubusercontent.com/assets/6366270/13884033/5d61d892-ed6f-11e5-84b6-4027e47a600e.png)

**Comment by tweekmonster** [comment]
Hmm.  Does deoplete.nvim modify the results dict?  If so, that may be the problem.

https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi.py#L183

On L183, try changing it to:

```python
out = cached.get('completions', [])[:]
```

To return a copy of the cache.

**Comment by zchee** [comment]
@tweekmonster Yes! I have found the cause.

If `menu` is empty, `deoplete.nvim` will be add `self.mark` to `menu`.
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/deoplete.py#L215-L221
It's not a bug. specification of `deoplete.nvim`.

So, We need a

```python
            out.append({
                '$type': _type,
                'word': word,
                'abbr': abbr,
                'kind': self.format_description(c.description),
                'info': docstring,
                # this line
                'menu': self.mark,
                'dup': 1,
            })
```

The problem does not occur.

**Comment by tweekmonster** [comment]
@zchee Great!  Seems strange that it was accumulating marks though.  Maybe that accumulation is a bug itself.  If deoplete.nvim was adding it, that means it was no longer empty and shouldn't add it again.

**Comment by zchee** [comment]
@tweekmonster Hmm...
Is that regex wrong?

```python
re.match(r'\[.*\]', context['candidates'][0].get('menu', ''))):
```

**Comment by tweekmonster** [comment]
@zchee It's not wrong.  The only issue I see with it is `re.match()` vs `re.search()` which may have unintended results.  https://docs.python.org/3.4/library/re.html#search-vs-match
For example, if `Base.mark` is set to `' [jedi]'` it won't match.

The issue I see is here:  https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/deoplete.py#L215

On that line, it only checks the first completion.  If there are multiple sources mixed in the results, and the first one doesn't have `menu` defined, all of them are updated even if other results already have the `menu` key:

```python
candidate['menu'] = source.mark + ' ' + candidate.get('menu', '')
```

**Comment by zchee** [comment]
@tweekmonster OK. I understand.
and, Thanks for good reference :)

but, If fix `deoplete.nvim` behavior to check all `candidates['menu']` in `context['candidates']` list, will reduce performance.

So, I think a better way is only to add `'menu': self.mark,` for now.
WDYT?

**Comment by tweekmonster** [comment]
@zchee That will work, but only for this case.  If another source comes before Jedi, I think duplicates will happen again.  I might be wrong since I don't know deoplete.nvim as well as you do.

For performance concerns, I think deoplete.nvim should not do the `menu` update on L215.  It should do it in `merge_results()` since there is already a loop occurring there: https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/deoplete.py#L248 (and it might need to happen on L238, too)

Actually I read over deoplete.py again, and I think I'm getting the indent scopes mixed up.  Are the results from multiple sources combined before L215?

**Comment by zchee** [comment]
@tweekmonster Yes, only for this case. I was known.

but, but... Now `deoplete-jedi` master branch will occur `self.mark` duplicate.
It will increase the other issue thread.

So, add `'menu': self.mark,` for now.
But, If I or you or Shougo resolved this problem someday, will revert (remove) `'menu': self.mark,`.
It's tentative workaround.

How would you like it? 🙏

**Comment by zchee** [comment]
@tweekmonster I also read `deoplete.nvim` sources.
I will do my best to resolve.

**Comment by tweekmonster** [comment]
> How would you like it? 🙏

あなたが上司です  :ok_hand:

**Comment by zchee** [comment]
@tweekmonster lol.
Committed: https://github.com/zchee/deoplete-jedi/commit/a5b10f6ef4b3c17d721702dee6dffeafa3f70675

To avoid misunderstanding of the other users, close once.
but, We should remember this matter.
