### ISSUE TITLE
Failed to start server

### ISSUE THREAD

**Issue by ProfessorChill** [zchee/deoplete-jedi#195]
# Problem summary
[https://i.imgur.com/qQM4fqo.png](Image of issue.)
When opening any python file I get the error displayed above.

## Environment Information
 * OS: Arch Linux x86_64
 * Neovim version: v0.3.1

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
set runtimepath+=~/.cache/dein/repos/github.com/zchee/deoplete-jedi
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

I honestly couldn't get the logs to generate.

**Comment by Shougo** [comment]
I cannot reproduce the error.
And please test the latest version of deoplete-jedi.
