### ISSUE TITLE
autocomplete not working on numpy arrays (but working on numpy.ndarray)

### ISSUE THREAD

**Issue by j9ac9k** [zchee/deoplete-jedi#200]
# Problem summary

Autocompletions not working for np.array variables

## Expected

```
a = np.array([1, 2, 3])
a.<auto-complete should get all numpy array methods>
```

## Environment Information

 * OS: macOS
 * Neovim version: 0.3.1

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
set runtimepath+=~/.config/nvim/plugged/deoplete-jedi/
let g:deoplete#enable_at_startup = 1

let g:python_host_prog = '/Users/ogi/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/Users/ogi/.pyenv/versions/neovim3/bin/python'

call plug#begin()
Plug 'davidhalter/jedi-vim'
  Plug 'lambdalisue/vim-pyenv'

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'zchee/deoplete-jedi', { 'for': 'python' }

call plug#end()

let g:jedi#completions_enabled = 0

" pyenv-jedi Allows changing of jedi versions
if jedi#init_python()
  function! s:jedi_auto_force_py_version() abort
    let g:jedi#force_py_version = pyenv#python#get_internal_major_version()
    let g:deoplete#sources#jedi#python_path = g:pyenv#python_exec
  endfunction
  augroup vim-pyenv-custom-augroup
    autocmd! *
    autocmd User vim-pyenv-activate-post   call s:jedi_auto_force_py_version()
    autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
  augroup END
endif

call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
call deoplete#custom#source('jedi', 'debug_enabled', 1)
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

[deoplete.log](https://github.com/zchee/deoplete-jedi/files/2443941/deoplete.log)
[nvim-log_py2_script.log](https://github.com/zchee/deoplete-jedi/files/2443942/nvim-log_py2_script.log)
[nvim-log_py3_rplugin.log](https://github.com/zchee/deoplete-jedi/files/2443943/nvim-log_py3_rplugin.log)
[nvim-log_py3_script.log](https://github.com/zchee/deoplete-jedi/files/2443944/nvim-log_py3_script.log)

## Steps to reproduce the issue after starting Neovim (required)

 1. Start neovim
 2. Edit a python file
 3. Select a Python environment with numpy installed (via pyenv activate)
 4. Import numpy, assign a variable as a numpy array and attempt to access that variables methods or attributes
 5. Declaring the variables as a `numpy.ndarray` does resolve correctly.

## Screen shot (if possible)

![screen shot 2018-10-03 at 2 34 32 pm](https://user-images.githubusercontent.com/646398/46440826-76709680-c719-11e8-98b3-22fe6175eaa2.png)
![screen shot 2018-10-03 at 2 34 25 pm](https://user-images.githubusercontent.com/646398/46440827-76709680-c719-11e8-9a37-48b0ed2f898d.png)

## Upload the logfile(s)

[deoplete.log](https://github.com/zchee/deoplete-jedi/files/2443941/deoplete.log)
[nvim-log_py2_script.log](https://github.com/zchee/deoplete-jedi/files/2443942/nvim-log_py2_script.log)
[nvim-log_py3_rplugin.log](https://github.com/zchee/deoplete-jedi/files/2443943/nvim-log_py3_rplugin.log)
[nvim-log_py3_script.log](https://github.com/zchee/deoplete-jedi/files/2443944/nvim-log_py3_script.log)

## Supplemental Information

Exact issue described shown here:
https://github.com/davidhalter/jedi/issues/372#issuecomment-275742630

Jedi author says that numpydoc has to be installed for it to work:
https://github.com/davidhalter/jedi/issues/372#issuecomment-372858394

**Comment by Shougo** [comment]
It is not deoplete-jedi's issue.
It is jedi's issue.
Closing.

**Comment by j9ac9k** [comment]
Not sure I agree, but I will post my fix in case anyone here comes across this issue.

I addressed this by running `pip install numpydoc` against the neovim3 virtualenv.  

Jedi's [documentation](https://jedi.readthedocs.io/en/latest/docs/features.html#type-hinting) states:

> In order to support the numpydoc format, you need to install the numpydoc package.

Once I did that, type completion on `numpy.array` worked great.

**Comment by Shougo** [comment]
OK.  jedi uses type information from the doc.

**Comment by j9ac9k** [comment]
I'm not sure.what the overlap between vim users and numpy/scipy/pandas users is, but I would encourage you to add numpydoc as a dependency to deoplete-jedi.
