### ISSUE TITLE
Template minimal init.vim uses deprecated function

### ISSUE THREAD

**Issue by tbttfox** [zchee/deoplete-jedi#208]
This template, provided when trying to write a new issue
```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

Which suggests using this line:
```call deoplete#custom#set('jedi', 'debug_enabled', 1)```

However, according to the deoplete help under deoplete-compatibility:
2017.07.22
* "deoplete#custom#set()" is deprecated.

From what I can tell, this is the line now.
```call deoplete#custom#option('jedi', 'debug_enabled', 1)```

**Comment by blueyed** [comment]
Yes, it is messy.
Please consider creating a PR if you figure it out.

**Comment by Shougo** [comment]
I have fixed it.
