### ISSUE TITLE
Virtualenv autocomplete

### ISSUE THREAD

**Issue by carlitux** [zchee/deoplete-jedi#21]
# Problems summary
There is a way to integrate with https://github.com/jmcantrell/vim-virtualenv so when autocomplete also do from there?

**Comment by zchee** [comment]
@carlitux Hi, Thanks for `Based on tern_for_vim and deoplete-jedi` :)
https://github.com/carlitux/deoplete-ternjs#deoplete-ternjs

I'll test it. but maybe already support original `virtualenv` environment.
See https://github.com/zchee/deoplete-jedi/issues/13#issuecomment-193994288
tweekmonster said 
> I'm having a similar issue using virtualenvs

but this issue has been solved in https://github.com/zchee/deoplete-jedi/commit/45a693debd75f0159a906556cea14ef3b205961b

**Comment by tweekmonster** [comment]
@zchee I believe he's asking about being able to change the virtualenv while Neovim is running.  I'm not sure if it's possible since Jedi reads the `VIRTUAL_ENV` environment variable to determine which Python interpreter to use.  Since deoplete.nvim runs as a Python subprocess, `os.environ` probably is not updated with the new `VIRTUAL_ENV` value.

@carlitux Have you tried switching virtualenvs with deoplete-jedi?  Does it simply not work or does it give wrong completions?

**Comment by carlitux** [comment]
@tweekmonster well really would be good if user the correct virtualenv like that plugin on startup so would autocomplete from it.

**Comment by tweekmonster** [comment]
@carlitux are you saying that you start Neovim without an active virtualenv?  Then you activate it later?

**Comment by carlitux** [comment]
@tweekmonster yeah, for example I am working with an django project but I don't want to add the neovim to requirements on the virtualenv or any other that is not related with the project.

**Comment by zchee** [comment]
@tweekmonster 
Thanks for details! I understand a little ( because I do not yet install virtualenv... 😱 )

@carlitux 
I do not know what is needed to resolve this problem.
However, Shougo does not use `virtualenv`, So not there is a possibility in the fix of deoplete core.
If resolve this issue, we need to be resolved in `deoplete-jedi` side.

**Comment by tweekmonster** [comment]
@carlitux Ohhh I understand now.  What I do is use separate virtualenvs for Neovim only (I work with dozens of virtualenvs).  I'm not sure if you can accomplish this easily with standard virtualenv.  I use pyenv to facilitate this, so your experience might differ:

- Create two virtualenvs.  One named `neovim2` using Python 2.X and another named `neovim3` using Python 3.X  (I use 2.7.11 and 3.4.3 respectively).
- Activate each virtualenv and install `neovim`.
- Add this to the `vimrc` file:

```vim
let g:python_host_prog = '/full/path/to/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/full/path/to/.pyenv/versions/neovim3/bin/python'
```

To get the paths with pyenv, you do something like this:

```shell
pyenv activate neovim2
pyenv which python
```

After this, you only need to activate `neovim2` and `neovim3` to update the neovim package.  Neovim will use which ever python interpreter is appropriate for the plugin.  Plugins that interact with your shell's active python interpreter should remain unaffected.  This effectively gives you `+python` and `+python3` to Neovim using clean package environments.

**Comment by tweekmonster** [comment]
@zchee I think deoplete is fine on its own.  His problem is that with every virtualenv he uses, he needs to install the neovim package so that remote plugins can work.

**Comment by zchee** [comment]
@tweekmonster 
> problem is that with every virtualenv he uses, he needs to install the neovim package so that remote plugins can work.

I got it.

@carlitux @tweekmonster 
Do I need to support it?

**Comment by tweekmonster** [comment]
@zchee I don't think so.  If the solution above works for @carlitux, I think it would only need a note in the `README.md`

**Comment by zchee** [comment]
@tweekmonster OK

@carlitux WDYT?

**Comment by carlitux** [comment]
that would work

**Comment by zchee** [comment]
@carlitux I merged pull request.
Close.
