### ISSUE TITLE
Upgrade python neovim package from 0.2.6 to 0.3.1 will break deoplete

### ISSUE THREAD

**Issue by jdhao** [zchee/deoplete-jedi#213]
I have found that updating neovim package from 0.2.6 to 0.3.1 breaks deoplete on both CentOS and Windows. The cause is that when upgrading to 0.3.1, Neovim python package is actually not installed, only the wheel info is present.

My environment is as follows:

+ Platform: CentOS 7 and Windows 10 (This issue occurs on both Platforms)
+ Neovim: 0.3.2
+ Python: 3.6.5 (provided by Anaconda)

It turns out that neovim package has been renamed to pynvim. I open an issue [here](https://github.com/neovim/pynvim/issues/380) and an answer from the dev. To successfully upgrade neovim package, we need to uninstall both neovim and pynvim and install it again.

It would be great the wiki [here](https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim#simple-setup) is updated accordingly.

**Comment by Shougo** [comment]
https://github.com/neovim/pynvim/issues/380

**Comment by Shougo** [comment]
It is not the problem of deoplete/deoplete-jedi.
