### ISSUE TITLE
Jedi autocomplete doesn't work

### ISSUE THREAD

**Issue by kef95** [zchee/deoplete-jedi#216]
# Problem summary
Yesterday I did `:PlugUpdate` and autocomplete stopped working. It would still show the dropdown list, but it would only match what I'm typing with keywords that are in the current file. The only way I could make it work is by doing Ctrl+X, Ctrl+O. So I think the issue itself is with Jedi?

## Expected
Both Jedi and deoplete should work.

## Environment Information

 * OS: Ubuntu 18.04.1 LTS
 * Neovim version: v0.3.1

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~~/.config/nvim/plugged/deoplete.nvim/
set runtimepath+=~~/.config/nvim/plugged/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('jedi', 'is_debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

 1. nvim in terminal
 2. :edit file.py
 3. Try to do any action that triggers the dropdown menu by editing the file

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/22250294/52183243-be5e1200-280e-11e9-885a-3b29d2a6111a.png)

## Upload the logfile(s)
[deoplete.log](https://github.com/zchee/deoplete-jedi/files/2826041/deoplete.log)

**Comment by Shougo** [comment]
I have tested it and it works for me.

**Comment by kef95** [comment]
Well any idea what might be wrong on my end?

**Comment by Shougo** [comment]
deoplete-jedi uses submodule.  You should check the submodule is the latest version.

**Comment by kef95** [comment]
It looks like it's the same version as the one in the git. I even removed all the plugins I have installed and reinstalled everything. Same issue

**Comment by Shougo** [comment]
Hm...  Jedi was upgraded in https://github.com/zchee/deoplete-jedi/pull/214.
It may have compatibility issue.

Please check the latest jedi works in your environment.

**Comment by Shougo** [comment]
Ah, and I have updated deoplete.
Please use the latest version.
