### ISSUE TITLE
python versions for virtualenv

### ISSUE THREAD

**Issue by hros** [zchee/deoplete-jedi#275]
The instructions recommend installing Python versions `2.7.11` and `3.4.4`

Is there a reason for these versions, or can I use the latest versions of Python?

If I only use Python 3.x do I need to install the 2.x virtualenv?

**Comment by Shougo** [comment]
> The instructions recommend installing Python versions 2.7.11 and 3.4.4

Really?  I cannot see the instruction.  Please upload it.
I will fix.

**Comment by hros** [comment]
In https://github.com/deoplete-plugins/deoplete-jedi/wiki/Setting-up-Python-for-Neovim#using-virtual-environments

**Comment by Shougo** [comment]
Fixed.
