### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by yevhen-m** [zchee/deoplete-jedi#28]
## Environment Information

 * OS: ubuntu 14.04
 * Neovim version: NVIM 0.1.3-dev

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
```

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/10185058/14310869/da260aac-fbec-11e5-931d-b4c4ac60625c.png)

**Comment by zchee** [comment]
@yevhen-m Maybe same as https://github.com/zchee/deoplete-jedi/issues/30

The debug information is less, So tries to resolve in that thread.

**Comment by zchee** [comment]
Solved https://github.com/zchee/deoplete-jedi/issues/30

Could you test it?
and, If you still have occur errors, Please reopen the issue.
