### ISSUE TITLE
Friendlier error message when jedi is not installed

### ISSUE THREAD

**Issue by balta2ar** [zchee/deoplete-jedi#53]
I've just ran neovim in conda env (virtualenv) and there was no jedi pip package installed. I had this in my :messages:

```
[deoplete] Traceback (most recent call last):
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/deoplete.py", line 272, in load_sources
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/deoplete.py", line 272, in load_sources
[deoplete]     source.on_init(context)
[deoplete]     source.on_init(context)
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 66, in on_init
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 66, in on_init
[deoplete]     self.debug_enabled, self.python_path)
[deoplete]     self.debug_enabled, self.python_path)
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 81, in start
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 81, in start
[deoplete]     show_docstring, debug, python_path)
[deoplete]     show_docstring, debug, python_path)
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 24, in __init__
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 24, in __init__
[deoplete]     python_path)
[deoplete]     python_path)
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 502, in __init__
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 502, in __init__
[deoplete]     self.restart()
[deoplete]     self.restart()
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 518, in restart
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 518, in restart
[deoplete]     self.version = stream_read(self._server.stdout)
[deoplete]     self.version = stream_read(self._server.stdout)
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 83, in stream_read
[deoplete]   File "/home/ybochkarev/.vim/bundle/.dein/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 83, in stream_read
[deoplete]     raise StreamEmpty
[deoplete]     raise StreamEmpty
[deoplete] deoplete_jedi.server.StreamEmpty
[deoplete] deoplete_jedi.server.StreamEmpty
[deoplete] Could not load source: deoplete_jedi.  Use :messages for error details.
[deoplete] Could not load source: deoplete_jedi.  Use :messages for error details.
Press ENTER or type command to continue
```

I'm not sure whether it's a deoplete_jedi or deoplete issue, but besides of messages being printed twice, the error message could be friendlier, say: "Could not import jedi python package. Install it using pip install jedi" or something along these lines.

After I had ran `pip install jedi`, the messages gone.

Thank you!

**Comment by tweekmonster** [comment]
Ah, so that's what #51 is about.  Jedi is vendored and doesn't need to be installed via `pip`.  How did you install this plugin?  If you cloned it, you would also need to run `git submodule update --init`

**Comment by balta2ar** [comment]
Today I switched from NeoBundle to dein.vim:
``` vim
call dein#add('zchee/deoplete-jedi')
```
Anyway, this isn't mentioned anywhere so it's not obvious what you need to do. I still think the error message could be more helpful.

**Comment by tweekmonster** [comment]
We're working on that.  Right now, it's not possible for the server to tell the client why it crashed.

Does dein clone the submodule correctly?

**Comment by balta2ar** [comment]
> Does dein clone the submodule correctly?

It should, according to this:
https://github.com/Shougo/dein.vim/blob/master/autoload/dein/types/git.vim#L131

Someone else complained here: https://github.com/Shougo/dein.vim/issues/113
But apparently Shougo could not reproduce it.

Anyway, it's not that big of a problem to me to do it manually once. Maybe mentioning that in the docs could be useful though.

**Comment by zchee** [comment]
@balta2ar Thanks for issue.

Hmm.. ok. I'm deoplete-jedi owner, also dein.vim collaborator.
So, I will try check and debug it. wait a moment....

**Comment by balta2ar** [comment]
@zchee Sure! I'm not insisting that it is dein's issue, this can easily be my local problem. I just wish I could have guessed about `git submodule update --init` by my own and didn't spend your time.

**Comment by Shougo** [comment]
@balta2ar You may need to reinstall deoplete-jedi.

**Comment by blueyed** [comment]
Let's close this for now.
There is better error handling in the pipeline, and it might have improved already anyway in this regard.

Please open a new issue otherwise.
