### ISSUE TITLE
Feature request: show function definition string when calling function

### ISSUE THREAD

**Issue by gboehl** [zchee/deoplete-jedi#54]
In vim-jedi, while typing variables in function a one-line pop-up with the function's variable appears, which I find very helpful. Is it possible to reimplement this feature? Unfortunately using both plugins and setting jedi#completions_enabled = 0 does not revoke this feature. 

Great work otherwise!

**Comment by Shougo** [comment]
You should use echodoc instead.
https://github.com/Shougo/echodoc.vim

vim-jedi documentation is tricky and easy to conflict other plugins.

**Comment by gboehl** [comment]
Perfect, that does what I want! Thanks a lot!
