### ISSUE TITLE
Feature request: show doc for instances and statements in popup

### ISSUE THREAD

**Issue by gboehl** [zchee/deoplete-jedi#55]
Hi,

I'm using the plugin with echodoc.vim to print function arguments (like in jedi-vim, where the variables of a function and statement are displayed in-line, which is a handy feature). It seems that echodoc uses jedi to access the docstring. This works fine for functions, but not for presumable instances or statements like numpy.arange(). Is there any way to fix this?

**Comment by Shougo** [comment]
It seems jedi just fails to generate the candidates.
