### ISSUE TITLE
newline character not shown in popup menu

### ISSUE THREAD

**Issue by petobens** [zchee/deoplete-jedi#57]
Consider the following minimal `init.vim`:

```vim
let $DOTVIM = expand('$HOME/.vim')

execute 'set runtimepath+=' . expand(
            \ '$DOTVIM/bundle/repos/github.com/Shougo/dein.vim')

call dein#begin(expand('$DOTVIM/bundle/'))
call dein#add('Shougo/deoplete.nvim')
call dein#add('zchee/deoplete-jedi')
call dein#add('Shougo/echodoc.vim')
call dein#end()
filetype plugin indent on

set completeopt=menuone,preview,noinsert
set noshowmode
set laststatus=2
set shortmess+=c
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python3'
let deoplete#sources#jedi#show_docstring = 1
let g:echodoc_enable_at_startup = 1
au CompleteDone * pclose!
```

Now  (as in the GIF and screenshot) open an empty python file and start typing `pri`. You wil see that deoplete correctly shows completion and signatures for `print` function. However the popup menu for the `end` argument is shown as `\x0a` instead of `\n`. This in turns makes `echodoc` fail (see the command line for this). I expect the popup menu (and echodoc) to show `\n`. Thanks in advance.
![screen shot 2016-09-15 at 17 31 58](https://cloud.githubusercontent.com/assets/2583971/18566544/b1292a78-7b6a-11e6-99d2-1132a971810b.png)

![sep-15-2016 17-31-41](https://cloud.githubusercontent.com/assets/2583971/18566531/a60c2622-7b6a-11e6-8082-33d5b7d7c742.gif)

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
I cannot reproduce it.
`\x0A` is printed in the popup menu and echo area.

**Comment by Shougo** [comment]
echodoc is improved.  Please check.

**Comment by tweekmonster** [comment]
Oh, I didn't see this issue before.  I actually made it display `\x0a` because echodoc used to split on `\\n` causing the issue described in OP.  Maybe something was double unescaping it?  This shouldn't be an issue any more, just mentioning it because of the irony :)

**Comment by petobens** [comment]
Thank you!!
