### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by wention** [zchee/deoplete-jedi#58]
# Problems summary

CPU up to 100% about two min
## Environment Information
- OS:ubuntu 15.04
- Neovim version: 0.1.6-dev
## Provide a minimal init.vim with less than 50 lines (Required!)

``` vim
" Your minimal init.vim
        " for python
        call dein#add('zchee/deoplete-jedi', {
                        \ 'depends': 'deoplete.nvim',
                        \ 'on_event': 'InsertEnter',
                        \ 'on_ft': 'python',
                        \ })

```
## The reproduce ways from neovim starting (Required!)
1. nvim get-pip.py
2. and type " import "
## Screen shot (if possible)

![image](https://cloud.githubusercontent.com/assets/5981572/18605433/ffb0a0da-7cc4-11e6-9a0f-1dbe8bf69423.png)
![image](https://cloud.githubusercontent.com/assets/5981572/18605446/2b0b7f3e-7cc5-11e6-878d-b508874178e2.png)
## Upload the log file

THE LOG IS TOO LARGE. 
PLEASE!! rename it with log_5970.tar.xz first.

[log_5970.zip](https://github.com/zchee/deoplete-jedi/files/477946/log_5970.zip)

WISH HELP TO YOU!

**Comment by Shougo** [comment]
What is get-pip.py?

**Comment by wention** [comment]
@Shougo  a script help to install pip

**Comment by Shougo** [comment]
https://bootstrap.pypa.io/get-pip.py

It is 1.5MB.  Too huge.
deoplete-jedi should skip the analysis.

**Comment by hackaugusto** [comment]
I'm having the same issue with a small or empty file:

- start `nvim -u init.vim t.py` ![nvim_before_insert](https://cloud.githubusercontent.com/assets/310139/23436568/c5ea109c-fde9-11e6-81c9-7897e6934613.png)
- enter insert mode and insert a new line ![nvim_after_insert](https://cloud.githubusercontent.com/assets/310139/23436565/c0f1c7b0-fde9-11e6-8bf4-e32f4927391a.png)

For some reason the python3 will spawn  subprocesses and the python2 will use 100% of the cpu. neovim interface will block at this point and it won't be usable.

init.vim:
```
" plugins
let s:plugins_base_dir=$HOME . "/.config/nvim/plugins"
let s:dein_dir=s:plugins_base_dir . "/repos/github.com/Shougo/dein.vim"

" use the system-wide python and the python-neovim package
let g:python_host_prog='/usr/bin/python2'
let g:python3_host_prog='/usr/bin/python3'

exe "set runtimepath+=" . s:dein_dir
set completeopt+=noinsert

if dein#load_state(s:plugins_base_dir)
  call dein#begin(s:plugins_base_dir)

  call dein#add(s:dein_dir)

  " completion
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('zchee/deoplete-jedi')

  call dein#end()
  call dein#save_state()
endif

call deoplete#enable()

let g:jedi#completions_enabled = 0
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#goto_command = 'gd'
let g:jedi#goto_assignments_command = 'ga'
let g:jedi#goto_definitions_command = ''
let g:jedi#usages_command = ''
let g:jedi#rename_command = '<leader>r'
let g:jedi#rename_command = ''
let g:jedi#show_call_signatures = 1
let g:jedi#show_call_signatures_delay = 100
let g:jedi#smart_auto_mappings = 0
```

versions:

```
> nvim --version
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

```
> /usr/bin/python3 --version
Python 3.6.0
```

```
> /usr/bin/python2 --version
Python 2.7.13
```

```
dein.vim: 728f8296f0973c18f6184c0631a6091469c55430
deoplete.vim: 7a9865ae3db5ebed3c5b96f48ed3d769a99c72cf
deoplete-jedi: a4dd511535a6fe06717a7bd2d680b9b87ade595d
```

**Comment by Shougo** [comment]
@hackaugusto deoplete and deoplete-jedi does not spawn Python2 interface.
I think other plugins use it.
You should check your init.vim.

**Comment by hackaugusto** [comment]
Humm, it could be this issue: https://github.com/davidhalter/jedi-vim/issues/687

I thought the command `vim -u init.vim` was sufficient for executing a vim from a new configuration, sorry about that.

**Comment by blueyed** [comment]
For Jedi: https://github.com/davidhalter/jedi/issues/878

**Comment by Shougo** [comment]
> Humm, it could be this issue: davidhalter/jedi-vim#687

So, it is not deoplete-jedi problem.

**Comment by blueyed** [comment]
I had bisected it in Jedi, and it is probably a newer issue then the reported one.

I think deoplete-jedi should abort after some timeout to prevent this and report an error with traceback. /cc @tweekmonster

**Comment by tweekmonster** [comment]
@blueyed It's logged in #112 but not reported to Vim's message area.  I couldn't get that to work for some reason without killing Neovim's python host.

**Comment by zhou13** [comment]
@tweekmonster I don't think adding a timeout is a good solution for this problem: it will just stop completion for this file totally and have side effect #124.  It is better just stopping the completion totally when the input file is too large.

**Comment by Shougo** [comment]
I have added limit option in deoplete.
Please use it.

**Comment by blueyed** [comment]
For reference: https://github.com/Shougo/deoplete.nvim/commit/04de49e2a7480ac9142fc38faba0ed62a9547c32
