### ISSUE TITLE
Menu flickers while completing

### ISSUE THREAD

**Issue by alexlafroscia** [zchee/deoplete-jedi#6]
Hey! I was trying to make my own `jedi` package for Deoplete when I came across yours.  I replaced the regular `jedi-vim` package with this and am trying it out.  I noticed that completions seem to be working, and as I'm typing I'm getting suggestions based on what Jedi should suggest, but the menu only appears for a second and then flickers away.  Do you think this has something to do with this package in particular? Or is it probably a Deoplete bug?

**Edit**: I made a `.gif` to show you what I'm seeing.

![deoplete-jedi-bug mov](https://cloud.githubusercontent.com/assets/1645881/12996226/03a16424-d0fc-11e5-9658-712c48622d30.gif)

If I turn off this plugin, then I don't get any issues with Deoplete.

**Comment by shawnohare** [comment]
@alexlafroscia For what it's worth, I encountered similar behavior yesterday with deoplete-go.  https://github.com/zchee/deoplete-go/issues/40.

**Comment by alexlafroscia** [comment]
Huh, that does the trick for me, too!

**Comment by zchee** [comment]
@shawnohare Thanks follow comment :)
@alexlafroscia 
Interim workaround is set
```vim
set completeopt-=preview
```
and, use `echodoc.vim`
https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L750-L754
http://github.com/Shougo/echodoc.vim

I will check whether this problem occurs in other deoplete source.

**Comment by alexlafroscia** [comment]
What exactly does `echodoc` do?

**Comment by zchee** [comment]
@alexlafroscia Here is `echodoc.vim` behavior sample.
Check statusline. Displayed `re.match` information.

![screenshot 2016-02-13 05 28 01](https://cloud.githubusercontent.com/assets/6366270/13019427/bacdee76-d212-11e5-873c-6e1975163d0a.png)

Recommends this settings. Show both function documents and `mode`
```vim
set cmdheight=2
let g:echodoc_enable_at_startup = 1
```

**Comment by alexlafroscia** [comment]
Huh, interesting.

**Comment by zchee** [comment]
@alexlafroscia 
> I installed it but can't tell what it's doing, and there's no README or anything.

See `:help echodoc.txt` :)

**Comment by alexlafroscia** [comment]
My bad 😣

**Comment by Shougo** [comment]
Same problem and we cannot fix.
https://github.com/zchee/deoplete-go/issues/40

**Comment by Shougo** [comment]
@alexlafroscia 

Can you test the neovim patch? 
https://github.com/neovim/neovim/pull/4036

**Comment by alexlafroscia** [comment]
@Shougo that seemed to fix my issued with `deoplete-jedi`!

**Comment by alexlafroscia** [comment]
I'm not sure if this is the cause, but it seem like I can only select the first or last option from the completion menu now.  As soon as I select it, the option is inserted and the menu disappears.  Hitting `CTL-N` a second time starts to complete the next word instead of advancing to the next option for the original word.

**Comment by Shougo** [comment]
OK.  It should be merged.  Thanks.
