### ISSUE TITLE
How to enable debugging? deoplete#sources#jedi#debug_enabled vs deoplete's help

### ISSUE THREAD

**Issue by blueyed** [zchee/deoplete-jedi#62]
https://github.com/zchee/deoplete-jedi/blob/1607a657fb564e53caf44562d3ae77881690f186/rplugin/python3/deoplete/sources/deoplete_jedi.py#L54-L56:

```python
    def on_init(self, context):
        vars = context['vars']

    …
        self.debug_enabled = vars.get(
            'deoplete#sources#jedi#debug_enabled', False
        )
```

In Deoplete.load_sources `context` has `'custom': {'_': {}, 'jedi': {'debug_enabled': 1}}` here, but not in `context['vars']`.

So it turns out that you need to actually set `deoplete#sources#jedi#debug_enabled = 1`, and deoplete's help is wrong / does not apply to this plugin?!

> 		" Enable jedi source debug messages
		call deoplete#custom#set('jedi', 'debug_enabled', 1)

This also means the new / current issue template is wrong, and @ysolis figured this out to get the debug log for https://github.com/zchee/deoplete-jedi/issues/56#issuecomment-248626554?!

> call deoplete#custom#set('jedi', 'debug_enabled', 1)

FWIW, code seems to have been changed recently in https://github.com/Shougo/deoplete.nvim/commit/5939bfb109593167d1cd4f1d4fe46080f5be6f91 - is this relevant?! /cc @tweekmonster 

Is deoplete-jedi "just" not behaving according to deoplete's interface / help here?

**Comment by blueyed** [comment]
It also seems to not be possible to enable debugging for a running instance, right?
`let deoplete#sources#jedi#debug_enabled = 1` needs to be set before the source is loaded.

**Comment by Shougo** [comment]
For enable debugging:

```vim
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
call deoplete#custom#set('jedi', 'debug_enabled', 1)
```

**Comment by Shougo** [comment]
I get it.  It is deoplete-jedi bug.
