### ISSUE TITLE
Automatically inserting functions

### ISSUE THREAD

**Issue by alexlafroscia** [zchee/deoplete-jedi#7]
I've noticed that my function results in Deoplete seem to be inserting themselves when I don't want them to.

For example, if I start typing and Deoplete suggests a list of items, and the first one is a function from Jedi, as soon as I hit `<C-n>` to start navigating through the list, the item gets inserted.  I think this is due to the fact that the `(` is added automatically.  If I cycle through the list backwards, it correctly passes over other Deoplete options, and variables from Jedi, but as soon as it hits a function and the `(` is inserted, the behavior breaks.

I can't get the behavior to break all the time, but can upload a file and describe what I'm doing that triggers the undesired behavior.

The follow Python file shows the error:

```python
// error.py
def test_model(test_file_name):
    pass
```

If you place the cursor at the end of the file and write `test` I get a completion that looks like this:

![screen shot 2016-02-17 at 1 42 15 am](https://cloud.githubusercontent.com/assets/1645881/13101839/b32cf16e-d517-11e5-88f7-164a0e0c0920.png)

After pressing `<C-n>` I would expect the first item in the list to be highlighted, but not actually entered.  However, pressing `<C-n>` only once brings me to the following instead:

![screen shot 2016-02-17 at 1 43 36 am](https://cloud.githubusercontent.com/assets/1645881/13101861/e37a9eca-d517-11e5-857a-d0d87e903e55.png)

**Comment by nhooyr** [comment]
I think you're confused on how completion works in vim. Read up on `:help ins-completion-menu`

**Comment by alexlafroscia** [comment]
@nhooyr exactly

**Comment by nhooyr** [comment]
@alexlafroscia does this happen with manual completion?

**Comment by alexlafroscia** [comment]
@nhooyr what do you mean by `manual completion`?

**Comment by Shougo** [comment]
@alexlafroscia Please create minimal init.vim less than 50 lines and without the plugin manager configurations.
I will test it.

**Comment by alexlafroscia** [comment]
Alright, so assuming you're using `vim-plug` for addon management, the following configuration shows the error:

```vim
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

let &runtimepath .= "," . $DOTFILES . "/nvim"

call plug#begin()
Plug 'airblade/vim-gitgutter'
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-jedi',               { 'for': 'python' }
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources.python = ['jedi', 'ultisnips']
```

I ran the command as `nvim -u init.vim error.py` where `init.vim` has the contents listed above.  Note, I had to run `:UpdateRemotePlugins` this first time, closed Neovim, and then ran the same command again.

The issue seems to be `vim-gitgutter`, strangely enough.  Using my normal configuration, removing that single plugin fixed the problem.

**Comment by Shougo** [comment]
OK.  I think it is vim-gitgutter's bug.
It is not deoplete-jedi's problem.  Closing.

https://github.com/airblade/vim-gitgutter/issues/310

**Comment by alexlafroscia** [comment]
👍 thanks!
