### ISSUE TITLE
Only show docstrings if they are not empty

### ISSUE THREAD

**Issue by blueyed** [zchee/deoplete-jedi#70]
Given a file like the following and `let deoplete#sources#jedi#show_docstring = 1` it would be nice if the completion for `bar` would not open the preview window with the docstring, since there is nothing to display.

``` python
def foo():
    """foo"""

def bar():
    pass

fo
ba
```

**Comment by tweekmonster** [comment]
I figured out how to fix this, but I'm not sure if it should have a separate option.  I don't use the preview window for completions, but I always thought the value of using it was to display the function's signature.  So, wouldn't people who have `preview` enabled in `completeopt` still want to see the function signature even without a docstring?

Maybe your problem with it is that it doesn't have any arguments?  I could see how that would make it a pointless preview.

**Comment by blueyed** [comment]
> display the function's signature

Oh, right.  I am using jedi-vim for that part presumably, which allows to show annotations using concealing or in the command line.  It is sadly broken in Neovim since a while for me (https://github.com/neovim/neovim/issues/5364) though.

Yes, in the example there are no arguments.
What about not showing it if there is no doc and no args then?

OTOH I see the arguments/signature in the completion menu already?!  (IIRC that might be another option though?!)

**Comment by tweekmonster** [comment]
I thought about this and I think it'll be best to have an option for this: `deoplete#sources#jedi#show_docstring_sig`.  Try out the referencing branch above and set that option to `0`.

You may want to backup `~/.cache/deoplete/jedi` beforehand if you want to return to the master branch.  I refactored it a bit so it'll be easier to change final output of `gather_completions()`, but the cached data is very different and won't be backward compatible.

An incidental change is that non-functions/classes will also display their docstrings in the preview window now.

> which allows to show annotations using concealing

Is there a way to trigger this without enabling jedi-vim's completions?  I missed this feature :(

> OTOH I see the arguments/signature in the completion menu already?!

There's no guarantee that the completion menu will display the full function signature.  Regardless of the different ways people can display function signatures, I think Vim's preview window is the default and most generic method for doing so.  I don't want to take away the "pure" method by default and rustle someone's jimmies.

**Comment by blueyed** [comment]
> Is there a way to trigger this without enabling jedi-vim's completions?

Completions do not have to be enabled for that.
I use jedi-vim for that and e.g. the goto and show usages.

**Comment by tweekmonster** [comment]
Ah, I use those, too.  But, I was hoping there was a way to manually display the vim-jedi's [`show_call_signatures()`](https://github.com/davidhalter/jedi-vim/blob/f95ac1e8e0a08c2d4a049519433d48fb07453e29/jedi_vim.py#L353) without using its completions.

**Comment by Shougo** [comment]
jedi-vim changes the buffer and uses conceal hacks.  It conflicts with other plugins or settings.
I think using echodoc plugin is better choice.

**Comment by tweekmonster** [comment]
@Shougo I use echodoc, but I like vim-jedi's display of call signature better because it's more aware of the function and its arguments.  It's a shame that it has to use a conceal hack to achieve it though.

What I don't like about echodoc is that it loses the function signatures because of new completions.  Something like `func1(func2(` will show `func2(a, b, c)` in the command line, but when I close `func2()`, the signature for `func1()` is lost.  Or if I perform another completion like `func1(func2(var`, I lose the signature for `func2()`.

**Comment by Shougo** [comment]
> What I don't like about echodoc is that it loses the function signatures because of new completions. Something like func1(func2( will show func2(a, b, c) in the command line, but when I close func2(), the signature for func1() is lost. Or if I perform another completion like func1(func2(var, I lose the signature for func2().

Yes, I know the problem.
The pull request is wellcome.

**Comment by blueyed** [comment]
@tweekmonster 
> without using its completions

`let g:jedi#completions_enabled = 0` ?

@Shougo 
> jedi-vim changes the buffer and uses conceal hacks

let g:jedi#show_call_signatures = 2

**Comment by tweekmonster** [comment]
> The pull request is wellcome.

@Shougo Yes, it's on my todo but the source is a little difficult for me to understand right now since I haven't studied it yet.  That's why I haven't created an issue 😅

> let g:jedi#completions_enabled = 0

@blueyed I have that `let g:jedi#show_call_signatures = 1` and `call jedi#configure_call_signatures()`.  Still nothing.  It only seems to appear when I enable vim-jedi's completions.

Back on topic: have you tried the `cache-refactor` branch?

**Comment by blueyed** [comment]
@tweekmonster 
Tried the branch (08e6009):
For entries without a docstring the preview window stays open (which makes sense to avoid flickering, but is not cleared).  When selecting an entry with docstring it flickers though (cannot really say if that was the case before though).

Then I was not getting any completions anymore (after suspend/hibernate - could that have an influence?!):
```
2016-09-29 21:30:55,692 DEBUG    (deoplete.jedi.cache) Input: "user=admin_us"
2016-09-29 21:30:55,693 DEBUG    (deoplete.jedi) Key: ('493a6c7022a908e78abcf351631a62a9', ('conftest', 'admin_user_and_renter_of_another_org'), 'vars'), Refresh: True, Wait: True
2016-09-29 21:30:55,694 DEBUG    (deoplete.jedi.Thread-1) Got work
2016-09-29 21:30:55,694 DEBUG    (deoplete.jedi.Thread-1) Worker error
Traceback (most recent call last):
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 53, in run
    self.out_queue.put(self.completion_work(*work), timeout=0.5)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 33, in completion_work
    filename)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 499, in completions
    stream_write(self._server.stdin, args)
  File "/home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 100, in stream_write
    buffer.write(header + data)
BrokenPipeError: [Errno 32] Broken pipe
2016-09-29 21:30:57,699 INFO     (deoplete.jedi) gather_candidates t = 2012.431093ms, µ = 2014.522498ms, σ = 2.755063ms)
```

It seems to recover after the "Broken pipe", but there's a delay and it keeps like that.
I suggest creating a PR from your branch to speak on/about the code?!

@tweekmonster part 2:
Regarding jedi-vim: it is broken because of some issue in Neovim, where deoplete's rpc during CursorHoldI (or something similar) breaks CursorHoldI (which jedi-vim uses).  Are you saying that it works for you when you use `let g:jedi#completions_enabled = 0`?

**Comment by tweekmonster** [comment]
> I suggest creating a PR from your branch to speak on/about the code?!

Good idea.  I don't know why I didn't do that from the start.

> Are you saying that it works for you when you use let g:jedi#completions_enabled = 0?

Actually the opposite, it works fine with `let g:jedi#completions_enabled = 1`, even with deoplete-jedi enabled.  It just causes completions to be a little slower.

**Comment by blueyed** [comment]
Yeah, I've meant 1 - sorry.

**Comment by Shougo** [comment]
echodoc is improved by @tweekmonster .
@blueyed You should use it.

**Comment by Shougo** [comment]
It is implemented by echodoc.
