### ISSUE TITLE
Preview split window remains after function is written

### ISSUE THREAD

**Issue by pavloko** [zchee/deoplete-jedi#84]
Thanks for the great plugin.

# Problem summary
The preview split window doesn't disappear after function is already written.
## Expected
The preview should disappear.
## Environment Information

 * OS: MacOS Sierra
 * Neovim version: 0.1.5

## Provide a minimal init.vim with less than 50 lines (required)
The only fields I have set up in my init.vim are the following
```
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#show_docstring = 1
```

## Screen shot (if possible)
The Preview window still shows `cProfile.run()` function docstring. 
![Screenshot](https://cloud.githubusercontent.com/assets/12280422/19765975/f997b2ca-9c53-11e6-86d8-4a69a7c2e3b1.png)

**Comment by Shougo** [comment]
```vim
autocmd CompleteDone * pclose!
```

**Comment by sonic182** [comment]
How should I do this, I don't understand

```
autocmd CompleteDone * pclose!
```

**Comment by Shougo** [comment]
```vim
autocmd CompleteDone * pclose!
```

You can add the line in your vimrc.
