### ISSUE TITLE
deoplete-jedi doesn't show all completion candidates that jedi-vim can

### ISSUE THREAD

**Issue by monkoose** [zchee/deoplete-jedi#89]
# Problem summary
This issue needs a confirmation. Because i'm not sure is it something with my config or deoplete-jedi problem itself.
There is no candidates for something like django's `admin.site. ....`
or deoplete-jedi doesn't show candidates for statements inside django's classes, etc.
```
class BookAdmin(admin.ModelAdmin):
    list_display
```
![](http://i.imgur.com/nsmqIFp.png)

![](http://i.imgur.com/EfeoBQF.png)

## Expected
jedi-vim candidates 
![](http://i.imgur.com/Uy5kwyh.png)

![](http://i.imgur.com/2bfeqWR.png)
 * Neovim version:
0.1.6

**Comment by blueyed** [comment]
Confirmed/reproduced.

**Comment by Shougo** [comment]
@tweekmonster @zchee Ping

**Comment by tweekmonster** [comment]
Looking into this

**Comment by monkoose** [comment]
Thank you @tweekmonster 
And for your djangoplus too:)

**Comment by monkoose** [comment]
By the way this problem was not only for django.
Same problem was with importing numpy. And i bet with other packages.

**Comment by zchee** [comment]
@monkoose Thanks share the detail. Now has been merged #90. Try fetch the master branch.

@tweekmonster @blueyed @Shougo
I would appreciate your cooperation. Thanks.

**Comment by blueyed** [comment]
> I would appreciate your cooperation

There is nothing left to be done here, is there?
Or did I misunderstood, and you wanted to thank us? 😕 :)

**Comment by zchee** [comment]
@blueyed Oh? Did I say bad English? Sorry.
In other words, I am grateful for all your help.

**Comment by monkoose** [comment]
@tweekmonster  @blueyed @zchee Thanks again. Works perfect for described problems.

But tested with numpy(even larger package then django and more comlex) and seems like it still cant show some candidates that JEDI(and jedi-vim) can. Tested in atom and vscode too. They both can complete(atom need like 5-10 sec to actually recognize this candidates. Yes numpy is huge), vscode much faster but still delay 2-3 seconds before comletions show up.
I dunno - maybe it's too much for deoplete-jedi and deoplete itself? Because my neovim even freeze for few seconds when im trying to get this completions with jedi-vim
Some screenshots
deoplete-jedi
![](http://i.imgur.com/noOGWkW.png)
jedi-vim
![](http://i.imgur.com/9wwZ4Sd.png)
atom
![](http://i.imgur.com/yuk7Afq.png)

As you can see from jedi-vim screenshot actual path for sin is numpy.umath.sin. And as expecting deoplete-jedi completes it without a problem
![](http://i.imgur.com/4HT8vg6.png)

So i dont really know should we try to fix this. Because it's laggy. Just posted for the record.

**Comment by zchee** [comment]
@monkoose Oh, it's might create new issue thread is good. Could you create issue?

But deoplete-jedi was a freeze? IIRC deoplete-jedi using json cache for import module when the first method. numpy is larger is correct, but if already cached module method, take a 0.5 sec for show completion word list.
So, maybe deoplete-jedi was not freeze at your situation. Caused by wrong cached module method, or not support `as`...? not sure.
I'll check it.

Anyway, each major editor's results is a very good reference for us. IIRC there are no each editor's benchmark (like benchmark tool). Thanks.

**Comment by monkoose** [comment]
Then i will create new issue just with almost identical post.
