### ISSUE TITLE
Use deoplete.util.getlines instead of nvim.current.buffer

### ISSUE THREAD

**Issue by zchee** [zchee/deoplete-jedi#94]
As in https://github.com/zchee/deoplete-jedi/issues/58, `nvim.current.buffer` sometimes will freezing remote plugin if current buffer is large.
So need change to use `deoplete.util.getlines`.
I don't know `vim.call('getline', ...)` side effect for performance, but there is no way if fix Neovim core API or python-client module.

deoplete-go already dealt this problem.
But note that have own `Buffer` class for not need change the large fix such as `nvim.current.buffer.name` or etc. Just *copied* and some fix python-client buffer code.
And, I don't know that is a correct way and correct code. but now it works.
Also, `cache` is proof-concept, not used.
https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/deoplete_go/buffer.py

**Comment by Shougo** [comment]
OK.  I will fix the issue.
